{
  "hash": "132ddbfd2323e3ad68b8aaf3e0c7fbac",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"z-έλεγχος για διαφορά ποσοστών\"\nauthor: \"Κώστας Κούδας\"\ncache: TRUE\ndate: \"2026-02-11\"\nformat:\n  html:\n    toc: true\n    number-sections: true\n    fig-cap: true\n---\n\n\n\n\n::: {.cell}\n\n:::\n\n\nΣτην ενότητα [Τιμή σημαντικότητας – (p-τιμή)](tTest.html#2_Τιμή_σημαντικότητας_–_(p-τιμή)) εξετάσαμε το ενδεχόμενο το ποσοστό ενός χαρακτηριστικού σε ένα συγκεκριμένο δείγμα να διαφέρει από το ποσοστό αυτού του χαρακτηριστικού στον πληθυσμό. Στην παρούσα ενότητα θα εξετάσουμε το ενδεχόμενο τα ποσοστά δύο ανεξάρτητων δειγμάτων να διαφέρουν. Συγκεκριμένα, με αφορμή τις δημοτικές εκλογές του 2023, θα συγκρίνουμε τα ποσοστά αποχής σε δύο δήμους της Ελλάδας, Κεντρικής Κερκύρας και Πατρέων.\n\nΑρχικά, για εισάγουμε-υπολογίζουμε τα ποσοστά αποχής στους δύο αυτούς δήμους (από [εδώ](https://ekloges.ypes.gr/current/d/home/municipalities/9118/) κι [εδώ](https://ekloges.ypes.gr/current/d/home/municipalities/9134/)) γράφοντας:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkerkSyn <- 64576\nkerkApoxi <- kerkSyn-31005\nkerkPos <- kerkApoxi/kerkSyn\npatraSyn <- 165684\npatraApoxi <- patraSyn-89715\npatraPos <- patraApoxi/patraSyn\nkerkPos\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5198681\n```\n\n\n:::\n\n```{.r .cell-code}\npatraPos\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4585174\n```\n\n\n:::\n:::\n\n\nΟπότε βρίσκουμε 0.5198681 για την Κεντρική Κέρκυρα και 0.4585174 για την Πάτρα. Ήτοι η αποχή στην Κεντρική Κέρκυρα ήταν περίπου στο 52% και στην Πάτρα 46%. Φαίνεται διαφορετικό το αποτέλεσμα. Είναι όμως; Όπως ανέκαθεν, θα δεχτούμε ότι δεν υπάρχει καμία διαφορά στα δύο ποσοστά (μηδενική υπόθεση) και θα ψάξουμε να βρούμε ποια θα είναι η πιθανότητα δεδομένου αυτού να τύχουμε δείγματα με τέτοια διαφοροποίηση. Αν μας βγει ότι με αυτή την υπόθεση θα ήταν απίθανο να τύχουμε αυτά που συναντάμε, τότε αναγκαστικά αυτή θα απορριφθεί, καθόσον οδηγεί σε μη ρεαλιστικές παραδοχές. Αν μας βγει ότι δεν είναι απίθανο να τύχουμε αυτά που συναντάμε, τότε (τι να κάνουμε;) δεν μπορούμε να απορρίψουμε την υπόθεση της ισότητας των δύο ποσοστών.\n\nΤην εν λόγω πιθανότητα θα μας την υπολογίσει η συνάρτηση `p_timiDifPos(⏳⏳⏳,👩👩👩,⏰⏰⏰,👦👦👦)`, όπου:\n\n-   στη θέση του `⏳⏳⏳` θα γράψουμε το ένα ποσοστό, δηλαδή το `kerkPos` (0.5198681),\n\n-   στη θέση του `👩👩👩` θα γράψουμε το μέγεθος του ενός πληθυσμού, δηλαδή το `kerkSyn` (64576),\n\n-   στη θέση του `⏰⏰⏰` θα γράψουμε το άλλο ποσοστό, δηλαδή το `patraPos` (0.4585174) και\n\n-   στη θέση του `👦👦👦` θα γράψουμε το μέγεθος του άλλου πληθυσμού, δηλαδή το `patraSyn` (165684).\n\nΑυτή ορίζεται από τον κάτωθι κώδικα:\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_timiDifPos <- function(pos1, plithos1, pos2, plithos2) {\n  a <- abs(pos1-pos2)\n  pos <- (pos1*plithos1+pos2*plithos2)/(plithos1+plithos2)\n  s <- sqrt(pos*(1-pos)*(1/plithos1+1/plithos2))\n  2-2*pnorm(a/s)\n}\n```\n:::\n\n\nΈτσι, γράφοντας:\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_timiDifPos(kerkPos, kerkSyn, patraPos, patraSyn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\nεξάγεται ένα ολοστρόγγυλο μηδενικό. Αυτό σημαίνει ότι, αν θεωρήσουμε ότι τα ποσοστά αποχής σε Κεντρική Κέρκυρα και Πάτρα δεν διαφέρουν, τότε θα ήταν εντελώς απίθανο να τύχουμε τα συγκεκριμένα αποτελέσματα αποχής που βλέπουμε. Οπότε τελικά, ναι, διαφέρουν τα ποσοστά αποχής στην προκειμένη περίπτωση.\n\nΕίναι κάτι το ιδιαίτερο η περιοχή της Πάτρας έναντι όλης της υπόλοιπης Ελλάδας ή μήπως απλά διαφοροποιείται από την Κεντρική Κέρκυρα; Θα δοκιμάσουμε να συγκρίνουμε τα ποσοστά αποχής στην Πάτρα αυτή τη φορά με αυτά της Βόρειας Κέρκυρας. Συλλέγουμε δεδομένα από [εδώ](https://ekloges.ypes.gr/current/d/home/municipalities/9326/) και ακολούθως γράφουμε:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBkerkSyn <- 19531\nBkerkApoxi <- BkerkSyn-10579\nBkerkPos <- BkerkApoxi/BkerkSyn\nBkerkPos\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4583483\n```\n\n\n:::\n:::\n\n\nΟπότε μάς εμφανίζεται αποχή της τάξης του 46% (0.4583483). Η διαφορά με την αποχή στην Πάτρα είναι στο 4ο δεκαδικό ψηφίο, πράγμα που μπορεί να σημαίνει ότι αυτές οι δύο περιπτώσεις δεν είχαν διαφορά. Ας το ελέγξουμε:\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_timiDifPos(BkerkPos, BkerkSyn, patraPos, patraSyn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9642096\n```\n\n\n:::\n:::\n\n\nΗ p-τιμή προέκυψε 0.9642096, δηλαδή δεν είναι καθόλου απίθανο να τύχουμε αυτά που βλέπουμε, αν τα δύο ποσοστά δεν διαφέρουν. Επομένως δεν είναι δυνατόν να απορρίψουμε την υπόθεση ότι η αποχή στην Βόρεια Κέρκυρα δεν διαφέρει από την αποχή στην Πάτρα.\n\nΣυνολικά γράψαμε τον κώδικα:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkerkSyn <- 64576\nkerkApoxi <- kerkSyn-31005\nkerkPos <- kerkApoxi/kerkSyn\npatraSyn <- 165684\npatraApoxi <- patraSyn-89715\npatraPos <- patraApoxi/patraSyn\nkerkPos\npatraPos\np_timiDifPos <- function(pos1, plithos1, pos2, plithos2) {\n  a <- abs(pos1-pos2)\n  pos <- (pos1*plithos1+pos2*plithos2)/(plithos1+plithos2)\n  s <- sqrt(pos*(1-pos)*(1/plithos1+1/plithos2))\n  2-2*pnorm(a/s)\n}\np_timiDifPos(kerkPos, kerkSyn, patraPos, patraSyn)\nBkerkSyn <- 19531\nBkerkApoxi <- BkerkSyn-10579\nBkerkPos <- BkerkApoxi/BkerkSyn\nBkerkPos\np_timiDifPos(BkerkPos, BkerkSyn, patraPos, patraSyn)\n```\n:::\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}