{
  "hash": "5f9f4dd11ac01ff707321f95a335ceaa",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Εκτίμηση ποσοστού\"\nauthor: \"Κώστας Κούδας\"\ncache: TRUE\ndate: \"2026-02-11\"\nformat:\n  html:\n    toc: true\n    number-sections: true\n    fig-cap: true\n---\n\n\n\n# Επίπεδο εμπιστοσύνης\n\nΣε μία δημοσκόπηση, λοιπόν, στην ομάδα [Μαθηματικό Εργαστήρι](https://www.facebook.com/groups/119060981470596) του facebook [ρωτήθηκαν](https://www.facebook.com/groups/119060981470596/permalink/2811760268867307/) τα μέλη της αν θεωρούν ισοδύναμες τις εξισώσεις:\n\n$2x+\\tan(x)=6+\\tan(x)$ και $2x=6$.\n\nΚλήθηκαν λοιπόν να διαλέξουν ανάμεσα στις επιλογές:\n\n-   Δεν είναι ισοδύναμες, διότι αν εκληφθούν ως προτασιακοί τύποι, δεν έχουν το ίδιο σύνολο ορισμού.\n\n-   Είναι ισοδύναμες, διότι έχουν τις ίδιες ακριβώς λύσεις.\n\nΤην πρώτη επιλογή (δεν είναι ισοδύναμες) υποστήριξαν 56 συνάδερφοι, ενώ την δεύτερη (είναι ισοδύναμες) 48. Από αυτά υπολογίζουμε ότι η αναλογία του «δεν είναι ισοδύναμες» στο δείγμα μας ήταν:\n\n$$\\dfrac{56}{56+48}=0.5384615.$$\n\nΖητάμε να βρούμε πόσο σίγουροι μπορούμε να είμαστε ότι η αναλογία αυτής της άποψης στο σύνολο των μαθηματικών της χώρας δεν θα αποκλίνει από αυτή που βρήκαμε περισσότερο από π.χ. 2 ποσοστιαίες μονάδες (0.02). Αρχικά, βέβαια, διαγράφουμε τα προηγούμενα.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list = ls())\n```\n:::\n\n\nΓι’ αυτό το σκοπό θα φτιάξουμε μια συνάρτηση που κάνει αυτή τη δουλειά. Η συνάρτηση αυτή θα ονοματιστεί:\n`EpipEmpistPos(🍺🍺🍺, 👨👨👨, 🚂🚂🚂)`.\n\n-   Στη θέση του `🍺🍺🍺` γράφουμε το ποσοστό που βρήκαμε (δηλαδή το 0.5384615),\n\n-   στη θέση του `👨👨👨` γράφουμε το πλήθος των τιμών (των συμμετεχόντων μαθηματικών, δηλαδή 56+48=104) και\n\n-   στη θέση του `🚂🚂🚂` γράφουμε την απόσταση που θέλουμε να δούμε αν απέχει η πληθυσμιακή μέση τιμή από τη δειγματική (εδώ αυτή, όπως είπαμε, θέλουμε να είναι 2%=0,02).\n\nΈχουμε λοιπόν:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nEpipEmpistPos <- function(pososto, plithos, apost) {\n  s <- sqrt(pososto*(1-pososto)/plithos)\n  2*pt(apost/s,plithos-1)-1\n}\n```\n:::\n\n\nΟπότε γράφοντας:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nEpipEmpistPos(0.5384615, 104, 0.02)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.316709\n```\n\n\n:::\n:::\n\n\nεξάγεται η απάντηση 0.316709. Αυτό σημαίνει ότι μπορούμε να είμαστε 31.67% σίγουροι ότι η πραγματική αναλογία είναι μεταξύ των αριθμών:\n\n0.5384615-0.02 και 0.5384615+0.02,\n\nδηλαδή ανάμεσα στα ποσοστά:\n\n51.84% και 55.84%.\n\nΣυνολικά, ο κώδικάς μας ήταν ο παρακάτω:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list = ls())\nEpipEmpistPos <- function(pososto, plithos, apost) {\n  s <- sqrt(pososto*(1-pososto)/plithos)\n  2*pt(apost/s,plithos-1)-1\n}\nEpipEmpistPos(0.5384615, 104, 0.02)\n```\n:::\n\n\n\n# Διάστημα εμπιστοσύνης\n\nΣτην έρευνα [Estimating the Population Size of Female Sex Workerεκπορνευόμενων Tehran, Iran: Application of Directεπιλέχθηκανcapture Method](https://link.springer.com/article/10.1007/s10461-017-1803-9) γίνεται απόπειρα να εκτιμηθεί ο συνολικός αριθμός εκπορνευομένων γυναικών στην Τεχεράνη. Προς τούτο επιλέχθηκαν αρχικά τυχαία 247 ιερόδουλες, στις οποίες δόθηκαν κοντομάνικα μπλουζάκια, αφού τους έγινε ενημέρωση για την έρευνα που διεξάγεται. Για να βρεθεί ο συνολικός αριθμός των ιερόδουλων, αρκεί να βρούμε τι μέρος τους έχει λάβει μπλουζάκι. Αν π.χ. βρούμε ότι το 50% έχει πάρει μπλουζάκι, τότε οι ιερόδουλες της Τεχεράνης είναι 2·247=494.\n\nΓια να υπολογιστεί το εν λόγω ποσοστό έγινε μία ακόμα δειγματοληψία 8 μέρες μετά. Εκεί δόθηκαν βραχιολάκια σε 190 ιερόδουλες και τους έγιναν κάποιες ερωτήσεις, μεταξύ των οποίων και αν έλαβαν μπλουζάκι από την προηγούμενη έρευνα. 68 εξ αυτών απάντησαν πως είχαν λάβει, οπότε συμπεραίνουμε πως η συγκεκριμένη δειγματική αναλογία:\n\n\\dfrac{\\iota\\varepsilon\\rho o\\delta o\\upsilon\\lambda\\varepsilon\\varsigma \\ \\ \\mu\\varepsilon \\ \\ \\mu\\pi\\lambda o \\upsilon\\zeta\\alpha\\kappa\\iota}{\\sigma\\upsilon\\nu o \\lambda o \\ \\ \\iota\\varepsilon\\rho o\\delta o \\upsilon \\lambda\\omega\\nu}\n\nισούται με:\n\n\\dfrac{68}{190}=0.3578947\n\nΘα θέλαμε βάσει αυτής να κάνουμε μια εκτίμηση της πληθυσμιακής αναλογίας (άρα και του πραγματικού πλήθους των εκπορνευομένων γυναικών), για την οποία να είμαστε σίγουροι κατά 98%. Η πληθυσμιακή αναλογία, καθόσον ερευνήσαμε μεγάλο πλήθος ιερόδουλων (>30), περιμένουμε ότι θα είναι κοντά στην δειγματική. Πάμε όμως να δούμε πόσο κοντά θα είναι με σιγουριά 98%, αφού όμως διαγράψουμε τις προηγούμενες μεταβλητές:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list = ls())\n```\n:::\n\n\nΗ δουλειά που θέλαμε θα γίνει μέσω μιας συνάρτησης που θα φτιάξουμε, της `DiastEmpistPos(🍺🍺🍺,👨👨👨,🎲🎲🎲)`.\n\n-   Στη θέση του `🍺🍺🍺` γράφουμε το ποσοστό του δείγματος που βρήκαμε (εδώ το 0.3578947),\n\n-   στη θέση του `👨👨👨` θα πάει το πλήθος των τιμών (δηλαδή οι 190 ιερόδουλες) και\n\n-   στη θέση του `🎲🎲🎲` θα πάει η σιγουριά που θέλουμε να έχουμε (εν προκειμένω θέλουμε να είμαστε σίγουροι κατά 98%=0.98).\n\nΗ συνάρτησή μας είναι λοιπόν η:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDiastEmpistPos <- function(pososto, plithos, pith) {\n  s <- sqrt(pososto*(1-pososto)/plithos)\n  a <- (1-pith)/2\n  t <- qt(a, plithos-1, lower.tail=F)\n  m1 <- pososto-t*s\n  m2 <- pososto+t*s\n  c(m1, m2)\n}\n```\n:::\n\n\nΟπότε γράφουμε:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDiastEmpistPos(0.3578947, 190, 0.98)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2762973 0.4394921\n```\n\n\n:::\n:::\n\n\nΕξάγεται έτσι η διπλανή απάντηση, όπερ σημαίνει ότι μπορούμε να είμαστε σίγουροι κατά 98% ότι η (πληθυσμιακή) αναλογία των ιερόδουλων με μπλουζάκι στο σύνολο των ιερόδουλων της Τεχεράνης θα είναι ανάμεσα στις τιμές 0.2762973 και 0.4394921.\n\nΌμως μπλουζάκι πήραν 247 ιερόδουλες. Έτσι, αν αυτές είναι το 27-43% όλων των ιερόδουλων, τότε όλες οι ιερόδουλες της Τεχεράνης θα είναι ανάμεσα στις τιμές:\n\n$\\dfrac{247}{0.2762973}\\approx 562$   και $\\dfrac{247}{0.4394921}\\approx 894$.\n\nΔηλαδή οι ιερόδουλες της Τεχεράνης είναι από 562 έως 894 με 98% σιγουριά.\n\nΣυνολικά γράψαμε τον κώδικα:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list = ls())\nDiastEmpistPos <- function(pososto, plithos, pith) {\n  s <- sqrt(pososto*(1-pososto)/plithos)\n  a <- (1-pith)/2\n  t <- qt(a, plithos-1, lower.tail=F)\n  m1 <- pososto-t*s\n  m2 <- pososto+t*s\n  c(m1, m2)\n}\nDiastEmpistPos(0.3578947,190,0.98)\n```\n:::\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}