---
format:
  html:
    toc: true
    number-sections: true
    fig-cap: true
---


```{r, echo=FALSE, results='asis'}
cat(readLines("indeximage.svg"), sep="\n")
```

# {{< fa brands r-project >}}  Κούδας {.unnumbered}



-   [**Στοχαστικά Μαθηματικά**]{.smallcaps}

-   [**χωρίς... μαθηματικά**]{.smallcaps}

-   [**για κοινωνικούς επιστήμονες**]{.smallcaps}

-   [**με τη συνδρομή της R**]{.smallcaps}

##  {{< fa dice >}}  Γιατί Στοχαστικά Μαθηματικά; {.unnumbered}

Σε μια πρώτη ανάγνωση, τα Στοχαστικά Μαθηματικά θα έλεγε κανείς πως είναι ένα ύπουλο εργαλείο: εκεί που υπάρχει αβεβαιότητα και έλλειψη δεδομένων, έρχονται αυτά να δώσουν απαντήσεις. Με άλλα λόγια είναι ο Δούρειος Ίππος των επιστημών.

> Είναι χαρακτηριστικό του εκπαιδευμένου πνεύματος το ότι μένει ικανοποιημένο με το βαθμό ακρίβειας που επιτρέπει η φύση του ζητήματος, και δεν αναζητεί την απόλυτη ακρίβεια εκεί που είναι δυνατή μόνο η προσέγγιση της αλήθειας.
>
> *Αριστοτέλης*

Ναι, κάνουν αυτή τη δουλειά, αλλά τον να αρκεστούμε σε αυτά είναι σαν να φτιάχναμε έναν Δούρειο Ίππο, τον οποίο να βάζαμε ναι μεν μέσα στο κάστρο της Τροίας, αλλά από την άλλη να μην βγαίναμε ποτέ έξω από αυτόν και να καθόμασταν κλειδωμένοι μέσα του. Για να είναι, λοιπόν, τα Στοχαστικά Μαθηματικά χρήσιμα δεν θα πρέπει να φιλοδοξούν να υποκαταστήσουν τη θεωρητική ανάλυση στην όποια επιστήμη. Τα Στοχαστικά Μαθηματικά, κοντολογίς, είναι το διαθέσιμο εργαλείο όσο δεν έχουμε κάποια διαθέσιμη θεωρητική ανάλυση, αλλά ταυτόχρονα θα πρέπει να αποτελούν έναν μηχανισμό έμπνευσης για τη δημιουργία μιας γενικότερης θεωρητικής προσέγγισης και αξιολόγησης της ήδη υπάρχουσας.

> Είναι εύκολο να ψεύδεσαι χρησιμοποιώντας τη Στατιστική. Είναι δύσκολο να πεις την αλήθεια χωρίς αυτή.
>
> *Andrejs Dunkels*

Λίγο-πολύ τα ερωτήματα που καλούνται να απαντήσουν τα Στοχαστικά Μαθηματικά είναι τα εξής:

-   «Πόσο πολύ σχετίζονται αυτά τα δύο μεγέθη;» (βλ. π.χ. [Μέτρα συσχέτισης](metrasysxetisis.html))
-   «Πόσο πιθανόν είναι να τύχαμε ένα τόσο ακραίο ποσοστό σε μια έρευνα;» (βλ. π.χ. [t-έλεγχος για το ποσοστό](tTest.html))
-   «Ποιες είναι οι πιθανές πορείες ενός φαινομένου, αν θέλουμε να είμαστε 95% σίγουροι γι' αυτό που θα προβλέψουμε;» (βλ. π.χ. [Πρόβλεψη χρονοσειρών με μοντέλα ARIMA](arima.html)) κ.τ.λ.

Παρατηρούμε την απουσία απόλυτων προσδιορισμών: Ρωτήσαμε πόσο πολύ σχετίζονται, όχι αν σχετίζονται και περιμένοντας μιαν απάντηση «ναι/όχι». Παρατηρούμε τον πιθανοκρατικό χαρακτήρα των ερωτημάτων: Ρωτήσαμε πόσο πιθανόν είναι τα δεδομένα να επαληθεύουν τη θεωρία, όχι αν την επαληθεύουν και περιμένοντας μιαν απάντηση «ναι/όχι». Όλα αυτά αντικατοπτρίζουν τα μικρά βηματάκια ανάμεσα στην απόλυτη άγνοια και την απόλυτη γνώση.

## {{< fa hand-fist >}} Γιατί για κοινωνικούς επιστήμονες; {.unnumbered}

Τα Στοχαστικά Μαθηματικά μπορούν ν' αποτελέσουν χρήσιμο εργαλείο σε κάθε επιστήμη. Μπορούμε να βρούμε απαραίτητες εφαρμογές της από τη μελέτη οικοσυστημάτων, μέχρι τα πλάνα μιας τράπεζας. Όμως μία εφαρμογή της Στατιστικής που αφορά π.χ. τους πιγκουίνους είναι ίσως αδιάφορη π.χ. για έναν αναλυτή πιστωτικού κινδύνου κι επίσης δεν έχει να του πει και πολλά, καθόσον θα είναι εμποτισμένη με στοιχεία μιας επιστήμης που δε σχετίζεται με τη δικιά του, ενώ παράλληλα θα απουσιάζουν τα στοιχεία της δικιάς του επιστήμης.

Κατά την άποψη του γράφοντος δεν υπάρχει πιο βαρετό πράγμα από τα εφαρμοσμένα μαθηματικά χωρίς εφαρμογές. Συνεπώς, μια ενδιαφέρουσα θεματολογία των Στοχαστικών Μαθηματικών είναι αυτή που θα καταπιάνεται με ένα θέμα ενδιαφέρον και σχετικά κατανοητό σε όλους. Αυτό είναι η κοινωνιολογία.

> Σημαντική δράση είναι οτιδήποτε προωθεί την αυτοπεποίθηση, την αυτονομία, την πρωτοβουλία, την συμμετοχή, την αλληλεγγύη, τις εξισωτικές τάσεις και την αυτενέργεια των μαζών και οτιδήποτε συμβάλλει στον αποφενακισμό τους.
>
> *Κορνήλιος Καστοριάδης*

Ένας επιπλέον λόγος για τον οποίο επιλέχθηκαν οι εφαρμογές στις κοινωνικές επιστήμες είναι και η καθολική αξία που έχουν τα συμπεράσματά τους. Ναι, ο κόσμος θα είναι ομορφότερος με μια ιατρική επιστήμη καλύτερη. Θα είναι επίσης ομορφότερος και με μια κοινωνία πιο δίκαιη και πιο ορθολογική.

> Η ισχύς της πόλης είναι οι άντρες και όχι τα τείχη ούτε τα άδεια πλοία.
>
> *Νικίας, δια στόματος Θουκυδίδη*

## {{<fa calculator >}}  Γιατί χωρίς μαθηματικά; {.unnumbered}

Τα εργαλεία της Στατιστικής επεξεργάζονται αριθμητικά δεδομένα, φτιάχνουν σχήματα κτλ. Σε μια στημένη άσκηση από έναν καθηγητή τα νούμερα και τα σχήματα θα είναι εφικτά. Π.χ. θα χρειάζεται ο μαθητής να υπολογίσει την πράξη:

$$\dfrac{10+30+20+70+35}{5}$$

για να βρει την μέση τιμή κάποιων αριθμών. Η αξία της Στατιστικής όμως θα φανεί σε νούμερα και πλήθη που δεν έχουν στηθεί για να υπολογίζονται εύκολα. Εκεί επί παραδείγματι μπορεί να χρειαστεί να υπολογιστεί η μέση τιμή διακοσίων τετραψήφιων αριθμών. Αυτό δεν θα ήταν εφικτό κι ούτε ασφαλές να υπολογιστεί με το χέρι. Ακόμα και με υπολογιστή τσέπης θα ήταν δύσκολο.

> Κι έτσι που να χαμογελάνε οι άλλοι και να λένε «Τέτοια ποιήματα σου φτιάχνω εκατό την ώρα». Αυτό θέλουμε κι εμείς. Γιατί εμείς δεν τραγουδάμε για να ξεχωρίσουμε, αδελφέ μου, απ' τον κόσμο. Εμείς τραγουδάμε για να σμίξουμε τον κόσμο.
>
> *Γιάννης Ρίτσος*

Συν τοις άλλοις, τα μαθηματικά που απαιτεί η Στατιστική πιθανότατα ξεπερνάνε τις μαθηματικές δυνάμεις και τις γνώσεις του μέσου πολίτη που ενδιαφέρεται για τις κοινωνικές επιστήμες. Ίσως ακόμα κι ένας αριστούχος του σχολείου στα Μαθηματικά, να δυσκολεύονταν να παρακολουθήσει έναν στατιστικό συλλογισμό και να ανάλωνε τις πνευματικές του δυνάμεις στην πάλη με τα μαθηματικά σύμβολα και πράξεις πίσω από τα στατιστικά εργαλεία, παρά στην αξιοποίησή τους για κοινωνιολογικά συμπεράσματα.

Φυσικά, όταν λέμε «χωρίς μαθηματικά» δεν εννοούμε ότι δε θα υπάρχουν καν αριθμοί. Εννοούμε ότι θα χρειάζονται απλά μαθηματικά Ε' Δημοτικού. Να μπορεί ο αναγνώστης λόγου χάρη να καταλάβει ότι ισχύει 10\<12, αλλά όχι 12\<10. Ή π.χ. να καταλαβαίνει ότι το 20% των Ελλήνων δεν είναι 20 Έλληνες. Κοντολογίς, απλά μαθηματικά πραγματάκια.

Απλά μαθηματικά πραγματάκια, αλλά μπόλικη σκέψη. Διότι, ναι μεν δε θα δούμε εξωφρενικά μαθηματικά, αλλά αυτό δε σημαίνει ότι ο εγκέφαλος δεν μας χρειάζεται. Σε τελική ανάλυση, με την κοινωνία μας ασχολούμαστε. Δε θα σκεφτούμε;

##  {{<fa robot>}} Γιατί R; {.unnumbered}

Η {{< fa brands r-project >}} έρχεται να μας δώσει την δυνατότητα να εφαρμόσουμε την Στατιστική, να τη μεταφέρουμε από την θεωρία στην πράξη, χωρίς να απαιτεί σε πρώτο επίπεδο πολλά μαθηματικά. Είναι σαν ένα κομπιουτεράκι Στατιστικής. Ο αναγνώστης δεν έχει παρά να μάθει τα «πλήκτρα».

> Φαντάζομαι μια εποχή όπου θα είμαστε για τα ρομπότ ό,τι είναι τα σκυλιά για τους ανθρώπους, και εγώ στηρίζω τις μηχανές.
>
> *Claude Shannon*

Αξίζει να την προτιμήσει από άλλα πακέτα Στατιστικής, όπως το SPSS κατ' αρχάς επειδή είναι δωρεάν. Άλλα πακέτα, όπως το PSPP, είναι επίσης δωρεάν, αλλά υστερούν σε δυνατότητες και σε διαδικτυακή υποστήριξη. Κοινότητες, σελίδες και βιβλία που αφορούν την {{< fa brands r-project >}} υπάρχουν δεκάδες σε πολλές γλώσσες, στην περίπτωση που κάποιος χρειαστεί βοήθεια.

Ένα επιπλέον ζήτημα είναι η ευκολία στην χρήση. Για κάποιον που απλά θέλει να κάνει ένα πινακάκι εσόδων-εξόδων ο κώδικας της είναι άσκοπη ταλαιπωρία. Ένα φύλλο Excel κάνει εύκολα και γρήγορα τη δουλειά αυτή. Η αξία της {{< fa brands r-project >}} αρχίζει να φαίνεται όταν θελήσουμε να κάνουμε πολλαπλές επεξεργασίες σ' ένα πινακάκι, να φτιάξουμε περίπλοκα σχήματα κ.τ.λ.

##  {{< fa sailboat >}}  Πώς διαβάζω την παρούσα σελίδα; {.unnumbered}

Στην παρούσα σελίδα έγινε φιλότιμη προσπάθεια να απλοποιηθούν πολλές έννοιες των Στοχαστικών Μαθηματικών Αυτό όμως δε σημαίνει ότι μπορούσε να γίνει οσοδήποτε απλή θα θέλαμε η σελίδα. Ένας ανυπόμονος αναγνώστης δεν μπορεί να πιάσει ένα άρθρο στην τύχη και να βγάλει νόημα μόνο από αυτό. Ίσως σε κάποια άρθρα να είναι εφικτό αυτό, αλλά εν γένει θα απαιτούνται γνώσεις και δεξιότητες που έχουν καλλιεργηθεί σε άλλα άρθρα.

> Όλα πρέπει να γίνονται όσο πιο απλά είναι δυνατόν, αλλά όχι απλούστερα.
>
> *Albert Einstein*

Ίσως αυτό να απογοητεύσει κάποιους. Σε αυτούς θα πρέπει να υπενθυμίσουμε ότι και ένα παιδικό μυθιστόρημα να πιάσει κάποιος από τη μέση, δύσκολα (ίσως και καθόλου) θα βγάλει άκρη τι γίνεται. Γιατί θα έπρεπε να συμβαίνει διαφορετικά σε ένα βιβλίο Στοχαστικών Μαθηματικών;

Η διάρθρωσή της έχει ως εξής:

-   **Εργαλεία:** Εδώ παρουσιάζονται κάποια εργαλεία των Στοχαστικών Μαθηματικών και το πώς αυτά υλοποιούνται μέσω της {{< fa brands r-project >}}.

-   **Έρευνες:** Εδώ γίνεται χρήση των παραπάνω εργαλείων για την εξέταση διαφόρων κοινωνικών ζητημάτων. Ο κώδικας δεν φαίνεται στη σελίδα, όμως ο ενδιαφερόμενος αναγνώστης μπορεί να τον βρει στο [github](https://github.com/kkoudas01/r4social).

-   **Εντός εκτός κι επί τα αυτά:** Στην συγκεκριμένη ενότητα μπορεί να βρει κανείς είτε εφαρμογές της {{< fa brands r-project >}} που δεν σχετίζονται με τις κοινωνικές επιστήμες (π.χ. [διδακτική της Στατιστικής](linearSX.html)) είτε που έχουν σχέση με τις κοινωνικές επιστήμες, αλλά δεν βασίζονται στην {{< fa brands r-project >}} (π.χ. [μετατροπές πινάκων κατάλληλων για mathematica](dataMathematica.html)).

##  {{< fa book-skull >}}  Βιβλιογραφία {.unnumbered}

Η σελίδα αυτή βασίστηκε *εν μέρει* στην παρακάτω βιβλιογραφία-αρθρογραφία.

> Ο άνθρωπος που δεν διαβάζει ζει μόνο μια ζωή. Ο αναγνώστης ζει 5.000. Το διάβασμα είναι η αθανασία ανάποδα.
>
> *Umberto Eco*

-   Martin D. Landau και William R. Jones. A Hardy Old Problem. Mathematics Magazine, 54(4):230-232, 1983.
-   Φ. Κολυβά -- Μαχαίρα, Ε. Μπόρα -- Σέντα. Στατιστική. Εκδόσεις Ζήτη, 1995.
-   ∆ηµήτρης Καρλής. Πολυµεταβλητή Στατιστική Ανάλυση. Εκδόσεις Οικονοµικού Πανεπιστη- µίου Αθηνών, 2003.
-   Janet M. Box -- Steffensmeier, John R. Freeman, Matthew P. Hitt και Hon C. W. Pevehouse. Time Series Analysis for the Social Sciences Cambridge University Press, 2014.
-   Robert H. Shumway και David S. Stoffer. Time Series Analysis and Its Applications Springer, 2017.
-   Rob J. Hyndman και George Athanasopoulos. Forecasting: Principles and Practice !!!
-   Alan Julian Izenman. Modern Multivariate Statistical Techniques. Springer, 2008.
-   John S. Witte. Statistics. Wiley, 2017.
-   Frederick J. Gravetter, Larry B. Wallnau και Lori-Ann B. Forzano. Essentials of Statistics for the Behavioral Sciences. Cengage Learning, 2018.
-   Beáta Dávid και Tom A. B. Snĳders. Estimating the Size of the Homeless Population in Budapest, Hungary. Quality and Quantity, 36, 291--303, 2002.
-   Jeremy M. G. Taylor. Kendall's and Spearman's Correlation Coefficients in the Presence of a Blocking Variable. Biometrics, 43, 409-4016, 1987.
-   Manoochehr Karami1, Salman Khazaei, Jalal Poorolajal, Alireza Soltanian, Mansour Sajadipoor. Estimating the Population Size of Female Sex Worker Population in Tehran, Iran: Application of Direct Capture--Recapture Method. AIDS and Behavior, 21, 2394--2400, 2017.
-   Roger Koenker και Kevin F. Hallock. Quantile Regression. The Journal of Economic Perspectives, 15(4), 143-156, 2001.
-   Nicolas Guéguen και Céline Jacob. Clothing Color and Tipping: Gentlemen Patrons Give More Tips to Waitresses with Red Clothes. Journal of Hospitality & Tourism Research, 38(2), 2014.
-   Edwin B. Wilson. Probable Inference, the Law of Succession, and Statistical Inference. Journal of the American Statistical Association, 22(158), 209-212, 1927.
-   Carl J. Dunst και Deborah W. Hamby. Guide for calculating and interpreting effect sizes and confi dence intervals in intellectual and developmental disability research studies . Journal of Intellectual & Developmental Disability, 37(2), 89-99, 2012.
-   Haldun Akoglu. User's guide to correlation coefficients. Turkish Journal of Emergency Medicine, 18, 91-93, 2018.
-   Chen-Bo Zhong, Vanessa K. Bohns και Francesca Gino. Good Lamps Are the Best Police: Darkness Increases Dishonesty and Self-Interested Behavior. Psychological Science, 21(3), 2010.
-   Berna Yazici και Senay Yolacan. A comparison of various tests of normality. Journal of Statistical Computation and Simulation, 77:2, 175-183, 2006.
-   Christopher Thron και Vincent Miller. Persistent Confusions about Hypothesis Testing in the Social Sciences. Soc. Sci., 4, 361--372, 2015.
-   J. F. Ratcliffe. The Effect on the t Distribution of Non-Normality in the Sampled Population. Journal of the Royal Statistical Society. Series C (Applied Statistics), 17(1), 42-48, 1968.
-   Thomas Lumley, Paula Diehr, Scott Emerson και Lu Chen. The Importance of the Normality Assumption in Large Public Health Data Sets. Annual Review of Public Health, 23, 151-169, 2002.
-   William S. Cleveland. Visualizing Data. AT&T Bell Laboratories, 1993.
-   Jay Alan Weinstein. Apllying Social Statistics. Rowman & Littlefield Publishers, 2010.
-   Henk Tĳms. Understanding Probability. Cambridge University Press, 2007.
-   Timothy C. Urdan. Statistics in Plain English. Routledge, 2017.
-   James McClave και Terry Sincich. Statistics. Pearson, 2018.
-   E. T. Jaynes. Probability Theory, the logic of science. Cambridge University Press, 2003.

## 🧸 Περί εμού {.unnumbered}

Ονομάζομαι Κώστας Κούδας, προσπαθώ να έχω μια επαφή με όλες τις επιστήμες και κυρίως τα μαθηματικά, τα οποία και σπούδασα.

> Για όσα δεν μπορείς να μιλάς, καλύτερα να σωπαίνεις.
>
> *Ludwig Wittgenstein*

Διαχειρίζομαι επίσης τις σελίδες:

-   [Επιψαύσεις](https://epipsayseis.pages.dev/),
-   [Αρκούδα Καφέ](https://arkoudakafe.pages.dev/),
-   [Η σελίδα μου στο YouTube](https://www.youtube.com/channel/UCEUIw1C3gFrwi1j-0b6Te7A),
-   [Καθημερινές ερωτήσεις, επιστημονικές απαντήσεις,](https://episthmonikesapanthseis.wordpress.com/),
-   [Προσομοιώσεις με τη συνεισφορά της Python](https://python4simulation.wordpress.com/).

Τέλος, [εδώ](https://independent.academia.edu/%CE%9A%CF%8E%CF%83%CF%84%CE%B1%CF%82%CE%9A%CE%BF%CF%8D%CE%B4%CE%B1%CF%82) μπορεί να δει κανείς κάποια δικά μου και μη άρθρα.
