---
title: "Προβλέψεις στις πανελλήνιες"
author: "Κώστας Κούδας"
cache: TRUE
date: "`r Sys.Date()`"
format:
  html:
    toc: true
    toc-depth: 4
    number-sections: true
    fig-cap: true
---

```{r}
# Καθαρισμός μνήμης R.
rm(list = ls())
```


Ακούμε διάφορους συναδέρφους να προβλέπου τα θέματα. 

> Θα πέσει «ρυθμός μεταβολής.
>
> Θα πέσει «Θ.Μ.Τ.»
>
> κ.τ.λ.

Από τις εν λόγω μαντικές ικανότητες «τσιμπάνε» γονείς, «τσμπάνε» τα πιτσιρίκια, «τσιμπάνε» και οι συνάδερφοι που πρωτοβγαίνουν στο επάγγελμα. Με το πέρας της εξέτασης, με το άγχος να σε παραλύει ακόμα, ούτε που κάθεται κανένεας να σκεφτεί πως ο καθηγητής-μέντιουμ έπεσε έξω.

Εδώ θα πρέπει να σημειώσουμε πως για να κάνει κάποιος κάποια αξιοπρεπή πρόβλεψη απαιτούνται τουλάχιστον 30 μετρήσεις  (βλ. πίνακα @tbl-data)

| Προγνωστικό μοντέλο | Ελάχιστο πλήθος μετρήσεων (ιδανικές συνθήκες) |
|:---|:---|
| **t-test / ANOVA** | 30 (ανά ομάδα) |
| **Linear Regression** (Απλή Γραμμική) | 30 |
| **Multiple Linear Regression** (Πολλαπλή - π.χ. 5 μεταβλητές) | 50 - 100 |
| **Logistic Regression** (Δυαδική) | 100 (ή τουλάχιστον 10 γεγονότα ανά μεταβλητή) |
| **ARIMA** (Χρονοσειρές) | 50 (ιδανικά >100 για εποχικότητα/seasonality) |
| **Naive Bayes** | 100 |
| **Decision Trees** (Δέντρα Απόφασης) | 200 |
| **KNN** (K-Nearest Neighbors) | 200 |
| **SVM** (Support Vector Machines) | 300 - 500 |
| **Random Forest** | 500 |
| **XGBoost / Gradient Boosting** | 1.000 |
| **Neural Networks** (Απλά MLP) | 5.000 |
| **Deep Learning** (CNN / LSTM) | 10.000+ |

: Πόσες τουλάχιστον μετρήσεις απαιτούνται για κάθε προγνωστικό μοντέλο; {#tbl-data}

















