---
title: "Στοχαστικές Διαφορικές Εξισώσεις"
author: "Κώστας Κούδας"
cache: TRUE
date: "`r Sys.Date()`"
format:
  html:
    toc: true
    toc-depth: 4
    number-sections: true
    fig-cap: true
references:
  - id: karatzas1991
    type: book
    title: "Brownian Motion and Stochastic Calculus"
    author:
      - family: Karatzas
        given: Ioannis
      - family: Shreve
        given: Steven E.
    issued:
      - year: 1991
    publisher: "Springer"

  - id: tsay2010
    type: book
    title: "Ανάλυση Χρονοσειρών"
    author:
      - family: Tsay
        given: Ruey S.
    issued:
      - year: 2010
    publisher: "Εκδόσεις Τζιόλα"

  - id: steele2001
    type: book
    title: "Stochastic Calculus and Financial Applications"
    author:
      - family: Steele
        given: J. Michael
    issued:
      - year: 2001
    publisher: "Springer"

  - id: allen2010
    type: book
    title: "An Introduction to Stochastic Processes with Applications to Biology"
    author:
      - family: Allen
        given: Linda J. S.
    issued:
      - year: 2010
    publisher: "CRC Press"

  - id: ross2019
    type: book
    title: "Introduction to Probability Models"
    author:
      - family: Ross
        given: Sheldon M.
    issued:
      - year: 2019
    publisher: "Academic Press"
---


```{r}
#| echo = F
rm(list = ls())
```

# Εισαγωγή στις Σ.Δ.Ε.

Μια απλή Διαφορική Εξίσωση είναι η $x'=b(x,t)$ ή, κάνωντας χρήση διαφορικών, $dx=b(x,t)dt$. Αυτό μάς λέει με ποιον τρόπο μεταβάλλεται το $x$ μετά από κάποιο μικρό χρονικό διάστημα $dt$. Τι γίνεται, όμως, αν θέλουμε να βάλουμε έναν παράγοντα τυχαιότητας στον εν λόγω κανόνα μεταβολής;

Στην πραγματική ζωή, όμως, τίποτα δεν είναι απόλυτα ντετερμινιστικό. Τουλάχιστον βάσει του επιπέδου γνώσης που έχουμε ή που μπορούμε να διαχειριστούμε. Έτσι, μια νότα τυχαιότητας στην παραπάνω Δ.Ε. θα έδινε ένα άρωμα ρεαλισμού εντονότερο από πριν. Μια ιδέα είναι να αυξομοιώνεται το αποτέλεσμα βάσει ενός τυχαίου μικρού άλματος $dW_t$ διεσταλμένο βάσει μιας συνάρτησης $\sigma(X_t, t)$. Έτσι έχουμε την παρακάτω διαφορική εξίσωση και λέμε ότι η $X_t$ είναι μία διαδικασία Itô:

$$
dX_t = b(X_t, t)dt+\sigma(X_t, t)dW_t
$$

Στον παραπάνω τύπο το $W_t$ είναι μια διαδικασία Wiener (βλ. [@karatzas1991] σελ. 284 και [@tsay2010] σελ. 290). Δηλαδή έχει τις κάτωθι ιδιότητες (βλ [@ross2019] σελ. 608):

- $W_0=0$,
- οι διαφορές $W_{t_1}-W_{t_2}$ είναι ανεξάρτητες και με ίδια κατανομή, για κάθε $t_1< t_2$,
- η $W_t$ ακολουθεί την κανονική κατανομή με μέση τιμή $0$ και διασπορά $s^2 t$, για $t>0$.

Αν μία φορά οι Διαφορικές Εξισώσεις ήταν ζόρικες και απαιτούσαν ειδικά τεχνάσματα, οι Στοχαστικές Διαφορικές Εξισώσεις είναι για να απελπίζεσαι. Έτσι, δεν θα δώσουμε εδώ μια γενική λύση της παραπάνω Σ.Δ.Ε., αλλά μόνο σε κάποιες υποπεριπτώσεις της, και στη γενικότερη περίπτωση θα αρκεστούμε στη γραφική της επίλυση χρησιμοποιώντας μια διακριτοποιημένη εκδοχή της διαδικασίας Itô (βλ. [@tsay2010] σελ. 291):

$$
\Delta X=b(X_t,t)\Delta t+ \eta\sigma(X_t,t)\sqrt{\Delta t},
$$

όπου $\Delta X=X_{t+\Delta t}-X_t$ και $\eta\sim N(0,1)$.


# Το λήμμα Itô

Σημαντικό για την επίλυση κάποιων Σ.Δ.Ε., αλλά και για τον υπολογισμό διαφόρων χαρακτηριστικών της $X_t$ είναι το λήμα Itô (βλ. [@allen2010] σελ. 383 και [@tsay2010] σελ. 292), το οποίο δίνει το διαφορικό μιας συνάρτησης ($G$) των $X_t$ και $t$. Έτσι για την πραγματική συνάρτηση $G(x,t)$ με συνεχείς τις μερικές παραγώγους της ($\partial_t G$, $\partial_x G$ και $\partial_{xx}G$) έχουμε:

$$
\begin{align*}
dG(X_t,t)=&\left(\dfrac{\partial G(X_t,t)}{\partial t}+b(X_t,t)\dfrac{\partial G(X_t,t)}{\partial x}+\dfrac{\sigma^2(X_t,t)}{2}\dfrac{\partial^2 G(X_t,t)}{\partial x^2}\right)dt\\
&+\sigma(X_t,t)\dfrac{\partial G(X_t,t)}{\partial x}dW_t
\end{align*}
$$



# Μέση τιμή και διασπορά

Δεδομένου ότι η $X_t$ και το απειροστό $dW_t$ είναι ανεξάρτητα, όπως και τα $dW_t$ μεταξύ τους, έχουμε από την $dX_t = b(X_t, t)dt+\sigma(X_t, t)dW_t$

$$
\begin{align*}
&\mathbb{E}(dX_t) = \mathbb{E}\left(b(X_t, t)dt+\sigma(X_t, t)dW_t\right)\\
\Leftrightarrow & d\mathbb{E}X_t=\mathbb{E}b(X_t, t)dt+\mathbb{E}\left(\sigma(X_t, t)dW_t\right)\\
\Leftrightarrow & d\mathbb{E}X_t=\mathbb{E}b(X_t, t)dt+\left(\mathbb{E}\sigma(X_t, t)\right)\left(d\mathbb{E}W_t\right)\\
\Leftrightarrow & d\mathbb{E}X_t=\mathbb{E}b(X_t, t)dt
\end{align*}
$$

όπου η τελευταία ισότητα τεκμέρεται από το γεγονός $\mathbb{E}W_t=0$. Η σχέση $d\mathbb{E}X_t=\mathbb{E}b(X_t, t)dt$, που φτιάξαμε, δεν εμπεριέχει πουθενά στοιχεία Στοχαστικού Λογισμού. Είναι μια απλή Διαφορική Εξίσωση με άγνωστη συνάρτηση την $m(t)=\mathbb{E}X_t$.

Για τον υπολογισμό της $\operatorname{Var}(X_t)$, λόγω της:

$$
\operatorname{Var}(X_t)=\mathbb{E}X_t^2-(EX_t)^2
$$

και δεδομένου ότι έχουμε βρει την $\mathbb{E}X_t$, δεν έχουμε, παρά να βρούμε την $\mathbb{E}X_t^2$. Έτσι, λόγω του λήμματος Itô (όπου $G(x,t)=x^2$) έχουμε:


$$
dX_t^2=\left(2b(X_t,t)X_t+\sigma^2(X_t,t)\right)dt+2\sigma(X_t,t)X_tdW_t
$$

Έτσι, όπως πριν:

$$
\begin{align*}
&\mathbb{E}(dX_t^2) = \mathbb{E}\left(\left(2b(X_t,t)X_t+\sigma^2(X_t,t)\right)dt+2\sigma(X_t,t)X_tdW_t\right)\\
\Leftrightarrow & d\mathbb{E}X_t^2=\mathbb{E}\left(2b(X_t,t)X_t+\sigma^2(X_t,t)\right)dt+\mathbb{E}\left(2\sigma(X_t,t)X_tdW_t\right)\\
\Leftrightarrow & d\mathbb{E}X_t^2=\mathbb{E}\left(2b(X_t,t)X_t+\sigma^2(X_t,t)\right)dt+\mathbb{E}\left(2\sigma(X_t,t)X_t\right)\mathbb{E}\left(dW_t\right)\\
\Leftrightarrow & d\mathbb{E}X_t^2=\mathbb{E}\left(2b(X_t,t)X_t+\sigma^2(X_t,t)\right)dt
\end{align*}
$$

Η $d\mathbb{E}X_t^2=\mathbb{E}\left(2b(X_t,t)X_t+\sigma^2(X_t,t)\right)dt$ μια φυσιολογική Διαφορική Εξίσωση που μάς φανερώνει τη συνάρτηση $sq(t)=\mathbb{E}X_t^2$, ήπερ είναι το τελευταίο ληθαράκι, για να βρούμε την $\operatorname{Var}(X_t)$.

Ας δούμε τα παραπάνω με ένα παράδειγμα μιας Σ.Δ.Ε. Σε πρώτη φάση ας ρίξουμε μια ματιά στη συνήθη Διαφορική Εξίσωση:

$$
x'=\alpha\cdot(\mu-x), \ \alpha>0.
$$

Η φυσική της σημασία είναι προφανής: Η μεταβλητή $x$ έχει την τάση να επιστρέφει στο $\mu$, διότι:

- αν $x>\mu$, τότε $x'<0$, άρα η $x$ κατεβαίνει προς το $\mu$,
- αν $x<\mu$, τότε $x'>0$, άρα η $x$ ανεβαίνει προς το $\mu$.

Με διαφορικά η εν λόγω εξίσωση γράφεται $dx=\alpha(\mu-x)dt$. Θέλοντας να κρατήσουμε την προαναφερθείσα συλλογιστική επαναφοράς, αλλά να τη διαταράξουμε με λίγη τυχαιότητα, τότε έχουμε την εξίσωση Langevin, η λύση της οποίας καλέιται διαδικασία Ornstein-Uhlenbeck (βλ. [@tsay2010] σελ. 487-489):


$$
dX_t=\theta\cdot(\mu-X_t)dt+\sigma dW_t, \ \alpha,\sigma>0.
$$


Έχουμε, όπως πριν:

$$
\mathbb{E}\left(dX_t\right)=\mathbb{E}\left(\theta\cdot(\mu-X_t)dt+\sigma dW_t\right)\Leftrightarrow d\mathbb{E}X_t=\theta(\mu-EX_t)dt
$$

Θέτουμε $m(t)=\mathbb{E}X_t$, άρα έχουμε τη Διαφορική Εξίσωση:

$$
m'=\theta (\mu-m)
$$

με $m(0)=\mathbb{E}X_0=x_0$. Εύκολα βρίσκουμε ότι:

$$
m(t)=\mu+e^{-\theta t}\left(x_0-\mu\right)
$$

Για τη διακύμανση θα πάμε να υπολογίσουμε το $dX_t^2$, όπως είπαμε και στις γενικές οδηγίες. Λόγω του λήμματος Itô (όπου $G(x,t)=x^2$) έχουμε:


$$
dX_t^2=\left(2\theta (\mu-X_t)X_t+\sigma^2\right)dt+2\sigma X_tdW_t.
$$

«Κοπανάμε» $\mathbb{E}$ και στις δύο μεριές της παραπάνω εξίσωσης, οπότε έχουμε:

$$
\begin{align*}
&\mathbb{E}(dX_t^2) = \mathbb{E}\left(\left(2\theta (\mu-X_t)X_t+\sigma^2\right)dt+2\sigma X_tdW_t\right)\\
\Leftrightarrow & d\mathbb{E}X_t^2=\mathbb{E}\left(2\theta (\mu-X_t)X_t+\sigma^2\right)dt+\mathbb{E}\left(2\sigma X_tdW_t\right)\\
\Leftrightarrow & d\mathbb{E}X_t^2=\left(2\theta\mu\mathbb{E}X_t-2\theta\mathbb{E}X_t^2+\sigma^2\right)dt\\
\Leftrightarrow & d\mathbb{E}X_t^2=\left(2\theta\mu\left(\mu+e^{-\theta t}\left(x_0-\mu\right)\right)-2\theta\mathbb{E}X_t^2+\sigma^2\right)dt
\end{align*}
$$

Θέτοντας $sq(t)=\mathbb{E}X_t^2$ έχουμε τη συνήθη Διαφορική Εξίσωση:

$$
sq'(t)=2\theta\mu\left(\mu+e^{-\theta t}\left(x_0-\mu\right)\right)-2\theta sq(t)+\sigma^2
$$

Λύνοντας την παραπάνω Διαφορική Εξίσωση έχουμε:


$$
sq(t)=\frac{e^{-2\theta t}\left(\left(e^{\theta t}-1\right)\left(2\theta\mu^2\left(e^{\theta t}-1\right)+\sigma^2\left(e^{\theta t}+1\right)\right)+4\theta\mu x_0\left(e^{\theta t}-1\right)+2\theta x_0^2\right)}{2\theta}
$$

Άρα:

$$
\begin{align*}
\operatorname{Var}X_t&=\mathbb{E}X_t^2-(\mathbb{E}X_t)^2\\
&=\dfrac{(1-e^{-2\theta t})\sigma^2}{2\theta}
\end{align*}
$$

# Η εξίσωση Fokker-Plank για τη σ.π.π.

Δεδομένης της μη-επιλυσιμότητας της Σ.Δ.Ε. πολλάκις αρκούμαστε στο να βρούμε την κατανομή της $X_t$ κι όχι την $X_t$ την ίδια. Η συνάρτηση πυκνότητας πιθανότητας της $X_t$ (έστω $p(x,t)$) είναι λύση της κάτωθι Μερικής Διαφορικής Εξίσωσης (βλ. [@allen2010] σελ. 380 και 382), όπου ο αναγνώστης θα την βρει στη βιβλιογραφία είτε ως **εξίσωση Fokker-Plank** είτε ως **εξίσωση Kolmogorov ορθής φοράς**:

$$
\dfrac{\partial p(x,t)}{\partial t}=-\dfrac{\partial\left(b(x,t)p(x,t)\right)}{\partial x}+\dfrac{1}{2}\dfrac{\partial^2\left(\sigma^2(x,t)p(x,t)\right)}{\partial x^2}
$$

# Διάφορες λύσεις

Στην ενότητα αυτή θα παρουσιάσουμε διάφορα στοχαστικά μοντέλα κοινωνικών ή οικολογικών φαινομένων που να θεμελιώνονται με τη βοήθεια Σ.Δ.Ε.

Αντίστοιχα με τη στοχαστική παραγώγιση, έχουμε και τη στοχαστική ολοκλήρωση. Δεν θα επεκταθούμε εδώ σε ορισμούς και εξηγήσεις, θα αναφέρουμε μόνο ότι ισχύουν οι βασικές ιδιότητες των ολοκληρωμάτων που ξέρουμε (προ Θ.Θ.Ο.Λ.) και δύο βασικούς υπολογισμούς (βλ. [@tsay2010] σελ. 308-309 και [@allen2010] σελ. 384), που θα μας χρησιμεύσουν: 

$$
\int_{t_1}^{t_2}dG(X_t,t)=G(X_{t_2},t_2)-G(X_{t_1},t_1)
$$

και:

$$
\int_{t_1}^{t_2}W_sdW_s=\dfrac{W_{t_2}^2-W_{t_1}^2}{2}-\dfrac{t_2-t_1}{2}
$$





## Γεωμετρική κίνηση Brown

Σχεδόν από το λύκειο γνωρίζει κανείς το εκθετικό πληθυσμιακό μοντέλο, σύμφωνα με το οποίο η αύξηση ενός πληθυσμού είναι ανάλογη του μεγέθους του. Ένα απόλυτα λογικό μοντέλο, καθόσον, αν ο καθένας από εμάς τους $x$ Έλληνες κάνει από $2$ παιδιά, τότε η αύξηση του πληθυσμού μας (τα συνολικά παιδιά, δηλαδή) θα είναι $\Delta x=2x$. Σε μαθηματικό συμβολισμό έχουμε:

$$
dx=rxdt.
$$

Ας βάλουμε λίγο θόρυβο στο μοντέλο αυτό. Συγκεκριμένα, ας θεωρήσουμε ότι το εύρος των τυχαίων κινήσεων είναι ανάλογο του ληθυσμού, μια εύλογη υπόθεση, αν θεωρήσουμε ότι οι τυχαίες διακυμάνσεις οφείλονται σε κάποιους τυχαίους παράγοντες που αφορούν το *κάθε* ένα άτομο. Έτσι έχουμε την κάτωθι Σ.Δ.Ε.  (βλ. [@allen2010] σελ. 384-385), η οποία ακούς στο όνομα **γεωμετρική κίνηση Brown**. 

$$
dX_t=rX_tdt+cX_tdW_t.
$$

Θα εφαρμόσουμε το λήμμα  Itô για $G(x,t)=\ln x$. Οπότε έχουμε:

$$
\begin{align*}
d\ln X_t&=\left(rX_t\dfrac{1}{X_t}-\dfrac{c^2X_t^2}{2}\dfrac{1}{X_t^2}\right)dt+cX_t\dfrac{1}{X_t}dW_t\\
&=\left(r-\dfrac{c^2}{2}\right)dt+cdW_t
\end{align*}
$$

Ολοκληρώνοντας τις δύο μεριές από $0$ έως $t$ έχουμε:

$$
\ln X_t-\ln X_0=\left(r-\dfrac{c^2}{2}\right)t+cW_t.
$$

Άρα:

$$
X_t=X_0\exp\left(\left(r-\dfrac{c^2}{2}\right)t+cW_t\right).
$$

## Λογιστικό μοντέλο

(βλ. [@allen2010] σελ. 386-387)

## Διαδικασία Ornstein-Uhlenbeck

$$
dX_t=\theta\cdot(\mu-X_t)dt+\sigma dW_t, \ \alpha,\sigma>0.
$$

Για να τη λύσουμε  διαδικασία που θα ακολουθήσουμε μοιάζει με την παραγοντική ολοκλήρωση (βλ. [@steele2001] σελ. 139-140) μορφής:

$$
dX_t=(\lambda(t) X_t+\theta(t))dt+\sigma(t) dW_t
$$

Θα ψάξουμε λύσεις της O-U της μορφής (βλ. [@steele2001] σελ. 139-140):


# Τεστ Feller για εκρήξεις

Η μελέτη μας θα γίνει σε ένα διάστημα:

$$
I=(\ell,r)\text{, με }-\infty\leq \ell, r\leq+\infty
$$

Συγκεκριμένα, εν προκειμένω θα ασχοληθούμε με Σ.Δ.Ε. του τύπου:

$$
dX_t = b(X_t)dt+\sigma(X_t)dW_t
$$

Όπου $b, \sigma : I\to \mathbb{R}$ (βλ. [@karatzas1991] σελ. 329 και 342-343). Ο αναγνώστης ας παρατηρήσει ότι οι συναρτήσεις $b$ και $\sigma$ δεν έχουν πλέον δύο ορίσματα, αλλά ένα.

Θα μάς απασχολήσει ο χρόνος όπου η διαδικασία μας ($X_t$) χρειάζεται για να ξεφύγει εκτός του προκαθορισμένου διαστήματος $I$. Πιο φορμαλιστικά (βλ. [@karatzas1991] σελ. 343):

$$
S=\inf\{t\geq 0: X_t\notin I\}
$$

Αρχικά ορίζουμε  (βλ. [@karatzas1991] σελ. 339) τη *scale function*:

$$
p(x)=\int_{c}^{x}\exp\left(-2\int_{c}^{\xi}\dfrac{b(\zeta)}{\sigma^2(\zeta)}d\zeta\right)d\xi
$$

με $c\in\mathbb{R}$ αυθαίρετη σταθερά και υπό τις συνθήκες (βλ. [@karatzas1991] σελ. 343):

$$
\forall x \in I \left(\sigma^2 (x)>0\right)
$$
και:

$$
\forall x \in I , \exists  \varepsilon>0\text{ τέτοιο, ώστε }\int_{x-\varepsilon}^{x+\varepsilon}\dfrac{1+|b(y)|}{\sigma^2(y)}dy<+\infty
$$

Ακολούθως ορίζουμε (βλ. [@karatzas1991] σελ. 347):

$$
v(x)=\int_{c}^{x}p'(y)\left(\int_{c}^{y}\dfrac{2dz}{p'(z)\sigma^2 (z)}\right)dy.
$$

Το τεστ Feller (βλ. [@karatzas1991] σελ. 348) μάς λέει αν είναι πιθανό να έχουμε έκρηξη (με την έννοια ότι βγαίνει η $X_t$ εκτός του $I$), δηλαδή αν η πιθανότητα $\mathbb{P}(S<+\infty)$ είναι μη-μηδενική. Έτσι, **δεν** έχουμε έκρηξη (ήτοι $\mathbb{P}(S<+\infty)=0$), όταν:

$$
v(\ell+)=v(r-)=\infty,
$$

αλλιώς έχουμε έκρηξη.
