{
  "hash": "07f72be91bb66f940094cabe4f453945",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Κανονική κατανομή\"\nauthor: \"Κώστας Κούδας\"\ncache: TRUE\ndate: \"2026-02-11\"\nformat:\n  html:\n    toc: true\n    number-sections: true\n    fig-cap: true\n---\n\n\n\n\n::: {.cell}\n\n:::\n\n\n<mark>Έστω ότι έχουμε έναν πληθυσμό και παίρνουμε από αυτόν μεγάλα δείγματα συγκεκριμένου μεγέθους (>30) για να μετρήσουμε κάποια μεταβλητή. Οι μέσες τιμές αυτής της μεταβλητής από αυτά τα δείγματα ακολουθούν την **κανονική κατανομή**. Επίσης το άθροισμα των τιμών του κάθε δείγματος ακολουθεί την **κανονική κατανομή**.</mark>\n\nΣυγκεκριμένα, αν ξέρουμε την πληθυσμιακή μέση τιμή και την πληθυσμιακή τυπική απόκλιση τότε οι δειγματικές μέσες τιμές ακολουθούν μια πλήρως προσδιορισμένη κανονική κατανομή και τα αθροίσματα μιαν άλλη κανονική κατανομή.\n\nΑλλά ας το δούμε πιο συγκεκριμένα! Υποθέτουμε ότι έχουμε κάποιες μηλιές που παράγουν μήλα με μέσο βάρος 50 γραμμάρια και τυπική απόκλιση 10 γραμμάρια. Παίρνουμε ένα δείγμα 400 μήλων και ψάχνουμε (α’) το μέσο βάρος των μήλων του δείγματος και (β’) το συνολικό βάρος των μήλων του δείγματος. Αυτά τα μεγέθη θ’ ακολουθούν τις κανονικές κατανομές $\\mathcal{N}(50,\\frac{10}{\\sqrt{400}})$ και $\\mathcal{N}(50\\cdot 10,10\\sqrt{400})$ αντίστοιχα.\n\nΓια να δούμε καλύτερα πώς συμπεριφέρονται τα μέσα βάρη από τα μήλα, θα πάρουμε 1000 καφάσια με 400 μήλα έκαστο. Οπότε γράφουμε:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar( mfrow= c(2,2) )\nfor (i in 1:4) {\n  set.seed(100*i)\n  xilia_kafasia <- rnorm(1000, mean = 50, sd = 1/2) \n  hist(xilia_kafasia)\n}\n```\n\n::: {.cell-output-display}\n![](normalDist_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nΑυτό σημαίνει ότι ως επί το πλείστον το μέσο βάρος θα είναι 50±0.5 γραμμάρια, ενώ είναι εντελώς απίθανο να τύχουμε μέσο βάρος πάνω από 51 γραμμάρια σε κάποιο καφάσι με 400 μήλα.\n\nΑπό την άλλη, για το συνολικό βάρος του καφασιού γράφουμε:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar( mfrow= c(2,2) )\nfor (i in 1:4) {\n  set.seed(100*i)\n  xilia_kafasia <- rnorm(1000, mean = 500, sd = 200) \n  hist(xilia_kafasia)\n}\n```\n\n::: {.cell-output-display}\n![](normalDist_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nΑυτό σημαίνει ότι από τα 1000 καφάσια που εξετάσαμε, τα περισσότερα έχουν βάρος 500±50 γραμμάρια, ενώ είναι απίθανο να τύχουμε καφάσι με βάρος κάτω από 100 γραμμάρια.\n\nΠώς θα μπορούσαμε να βρούμε κάποιες πιθανότητες με περισσότερη ακρίβεια και χωρίς ιστογράμματα; Ας υποθέσουμε ότι θέλουμε να δούμε ποια είναι η πιθανότητα να τύχουμε καφάσι με μέσο βάρος μήλων 51 με 52 γραμμάρια. Προς τούτο γράφουμε:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(52, mean = 50, sd = 1/2)-pnorm(51, mean = 50, sd = 1/2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02271846\n```\n\n\n:::\n:::\n\n\nΒρίσκουμε 0.02271846, δηλαδή είναι 2.27% πιθανό να τύχουμε καφάσι με τέτοιο μέσο βάρος.\n\nΑπό την άλλη, για να βρούμε την πιθανότητα ένα καφάσι να ζυγίζει 50-150 γραμμάρια θα γράψουμε:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(150, mean = 500, sd = 200)-pnorm(50, mean = 500, sd = 200)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02783468\n```\n\n\n:::\n:::\n\n\nκαι θα βρούμε 0.02783468, δηλαδή μπορούμε να είμαστε 2.78% σίγουροι ότι θα τύχουμε καφάσι με τέτοιο βάρος.\n\nΣυνολικά ο κώδικας που γράψαμε είναι ο:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar( mfrow= c(2,2) )\nfor (i in 1:4) {\n  set.seed(100*i)\n  xilia_kafasia <- rnorm(1000, mean = 50, sd = 1/2) \n  hist(xilia_kafasia)\n}\nfor (i in 1:4) {\n  set.seed(100*i)\n  xilia_kafasia <- rnorm(1000, mean = 500, sd = 200) \n  hist(xilia_kafasia)\n}\npnorm(52, mean = 50, sd = 1/2)-pnorm(51, mean = 50, sd = 1/2)\npnorm(150, mean = 500, sd = 200)-pnorm(50, mean = 500, sd = 200)\n```\n:::\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}