{
  "hash": "e529a7d72e54d1a9b5841c08d4242388",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Κατανομή Poisson\"\nauthor: \"Κώστας Κούδας\"\ncache: TRUE\ndate: \"2026-02-15\"\nformat:\n  html:\n    toc: true\n    number-sections: true\n    fig-cap: true\n---\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n<mark>Ας υποθέσουμε ότι ένα γεγονός εμφανίζεται με έναν συγκεκριμένο μέσο ρυθμό σε κάποιο χρονικό διάστημα (ή σε κάποια περιοχή του χώρου). Το πλήθος των εμφανίσεων του γεγονότος αυτού σε αυτό το χρονικό διάστημα (ή σε αυτή την περιοχή του χώρου) ακολουθεί την **κατανομή Poisson**.</mark>\n\nΘα το δούμε καλύτερα με ένα παράδειγμα. Ας υποθέσουμε ότι σε ένα κατάστημα φθάνουν κατά μέσο όρο 8 πελάτες την ώρα. Αυτό δεν σημαίνει, φυσικά, ότι αποκλείεται κάποια συγκεκριμένη ώρα να μην μπει κανένας ή κάποια άλλη να μπουν 20 πελάτες. Λέμε ότι κατά μέσο όρο μπαίνουν 8 πελάτες. Επομένως αξίζει να δούμε πόσο πιθανό είναι να μπουν οι 20 πελάτες που λέγαμε ή να είναι άδειο το μαγαζί για μία ώρα. Το πλήθος των πελατών που εισέρχονται στο κατάστημα σε διάστημα μιας ώρας ακολουθεί την κατανομή Poisson, οπότε θα εξετάσουμε την κατάσταση γράφοντας:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar( mfrow= c(2,2) )\nfor (i in 1:4) {\n  set.seed(100*i)\n  xilies_ores <- rpois(1000, 8)\n  pin_syxn <- table(xilies_ores)\n  barplot(pin_syxn)\n}\n```\n\n::: {.cell-output-display}\n![](poisson_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nΒλέπουμε κατά συνέπεια ότι συνήθως το μαγαζί μέσα σε μία ώρα θα υποδέχεται 7-9 πελάτες, ενώ σπανίως θα δέχεται πάνω από 15.\n\nΑς πάμε να βρούμε τώρα πόσο πιθανό είναι να μπουν ακριβώς 11 πελάτες σε μία ώρα. Θα χρειαστούμε τη συνάρτηση `dpois()`, οπότε θα γράψουμε:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndpois(11, 8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.07219021\n```\n\n\n:::\n:::\n\n\nΈτσι βρίσκουμε 0.07219021, δηλαδή είναι κατά 7.22% πιθανό να εμφανιστούν ακριβώς 11 πελάτες σε μία ώρα.\n\nΣυνολικά ο κώδικάς μας ήταν:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar( mfrow= c(2,2) )\nfor (i in 1:4) {\n  set.seed(100*i)\n  xilies_ores <- rpois(1000, 8)\n  pin_syxn <- table(xilies_ores)\n  barplot(pin_syxn)\n}\ndpois(11, 8)\n```\n:::\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}