{
  "hash": "93f9a78573681379a12a9d3dee89bcc5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Ομοιόμορφη συνεχής κατανομή\"\nauthor: \"Κώστας Κούδας\"\ncache: TRUE\ndate: \"2026-02-15\"\nformat:\n  html:\n    toc: true\n    number-sections: true\n    fig-cap: true\n---\n\n\n\n\n::: {.cell}\n\n:::\n\n\n<mark>Διαλέγουμε στην τύχη έναν αριθμό ανάμεσα σε δύο άλλους. Οι αριθμοί αυτοί που διαλέγουμε έτσι ακολουθούν την **ομοιόμορφη κατανομή**.</mark>\n\nΑς υποθέσουμε, για παράδειγμα, ότι η Τροχαία στήνει μπλόκο κάπου σε έναν δρόμο 900 μέτρων. Το μπλόκο μπορεί να είναι οπουδήποτε στον δρόμο αυτό, άρα η θέση του μπορεί να είναι σε οσαδήποτε μέτρα από 0 έως 900 από την αρχή του δρόμου. Με άλλα λόγια, η θέση του είναι κάποια μέτρα στην τύχη στο διάστημα 0 έως 900 από την αρχή του δρόμου. Πόσο πιθανόν είναι, λοιπόν, η αστυνομία να βρίσκεται στη μία ή την άλλη θέση; Θα παρακολουθήσουμε τα μπλόκα αυτά για 1000 μέρες και θα επαναλάβουμε το πείραμα 4 φορές.\n\nΈτσι, γράφουμε:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar( mfrow= c(2,2) )\nfor (i in 1:4) {\n  set.seed(100*i)\n  xilies_imeres <- runif(1000, min = 0, max = 900) \n  hist(xilies_imeres)\n}\n```\n\n::: {.cell-output-display}\n![](uniformCont_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nΑπό αυτά τα ιστογράμματα βλέπουμε ότι δεν έχει εμφανή πιθανότητα παραπάνω να συναντήσει κανείς μπλόκο στα πρώτα 200 μέτρα, έναντι πχ στα επόμενα 200 μέτρα. Το ίδιο συχνά θα δει κανείς μπλόκο πχ στο κεντρικό διάστημα 400 με 500 μέτρα από την αρχή του δρόμου, και το ίδιο λίγο-πολύ συχνά θα δει κανείς μπλόκο σε κάποιο άλλο διάστημα πλάτους 100 μέτρων (για παράδειγμα στο 800-900).\n\nΠόσο όμως είναι η πιθανότητα να τύχουμε μπλόκο στο διάστημα 400-500; Γράφουμε:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npunif(500,  min = 0, max = 900)-punif(400,  min = 0, max = 900)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1111111\n```\n\n\n:::\n:::\n\n\nΟπότε βρίσκουμε 0.1111111, δηλαδή είμαστε κατά 11.11% σίγουροι ότι θα τύχουμε μπλόκο στο διάστημα αυτό. Στο ίδιο αποτέλεσμα, φυσικά, καταλήγουμε αν πάρουμε οποιοδήποτε άλλο διάστημα πλάτους 100 μέτρων, όπως πχ το 137-237:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npunif(237,  min = 0, max = 900)-punif(137,  min = 0, max = 900)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1111111\n```\n\n\n:::\n:::\n\n\nΑπό την άλλη, αν θέλαμε να ξέρουμε κάτι περισσότερο ακριβές, αν θέλαμε επί παραδείγματι το μπλόκο να είναι κάπου ανάμεσα στα 270-280 μέτρα, τότε γράφουμε:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npunif(280,  min = 0, max = 900)-punif(270,  min = 0, max = 900)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01111111\n```\n\n\n:::\n:::\n\n\nκαι βρίσκουμε 0.01111111, πράγμα που σημαίνει πολύ μικρότερη σιγουριά (1.11%) για το ότι θα βρίσκεται εκεί η αστυνομία.\n\nΌλος ο κώδικάς μας παρατίθεται πιο κάτω:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar( mfrow= c(2,2) )\nfor (i in 1:4) {\n  set.seed(100*i)\n  xilies_imeres <- runif(1000, min = 0, max = 900) \n  hist(xilies_imeres)\n}\npunif(500,  min = 0, max = 900)-punif(400,  min = 0, max = 900)\npunif(237,  min = 0, max = 900)-punif(137,  min = 0, max = 900)\npunif(280,  min = 0, max = 900)-punif(270,  min = 0, max = 900)\n```\n:::\n\n\n\n\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}