<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Κώστας Κούδας">
<meta name="dcterms.date" content="2026-02-15">

<title>Αποχή στις εκλογές – r-koudas</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-9e15f8fb9e1f2f288bfbe28f6ca11029.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-f66507dd18a11913968bbb28d4895645.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/quarto-contrib/fontawesome6-6.7.2/all.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/fontawesome6-6.7.2/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">



<meta property="og:title" content="r-koudas: Στοχαστικά Μαθηματικά χωρίς… μαθηματικά για κοινωνικούς επιστήμονες">
<meta property="og:description" content="Η σελίδα RΚούδας είναι μια σελίδα κατά βάση ανάλυσης κοινωνικών φαινομένων. Σε αυτήν αναλύονται κάποια κοινωνικά φαινόμενα ή επιδεικνύεται ο τρόπος να αναλυθούν.">
<meta property="og:image" content="social-card.png">
<meta property="og:site_name" content="r-koudas">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title"><i class="fa-brands fa-r-project" aria-label="r-project"></i>Κούδας</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./ergaleia.html"> <i class="bi bi-tools" role="img">
</i> 
<span class="menu-text">Εργαλεία</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./ereynes.html" aria-current="page"> <i class="bi bi-flask" role="img">
</i> 
<span class="menu-text">Έρευνες</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./entos_ektos.html"> <i class="bi bi-cup-hot" role="img">
</i> 
<span class="menu-text">Εντός εκτός κι επί τα αυτά</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./apoxi.html">Αποχή στις εκλογές</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ereynes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ΕΡΕΥΝΕΣ</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./apoxi.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Αποχή στις εκλογές</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pisa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Εξέταση αποτελεσμάτων PISA</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./workHexitPov.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Έξοδος από τη φτώχεια</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./gini.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Μετρώντας την ανισότητα (Gini)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bouleytesCor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Το πολιτικό προφίλ των Ελλήνων εστιασμένο στ’ αριστερά</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pothenesxes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Πόθεν Έσχες βουλευτών</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./happy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Τι φέρνει την ευτυχία;</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./axiologisiDimon.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Αξιολόγηση Δημόσιων Υπηρεσιών</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pothenesxes2024.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Περιουσιακά στοιχεία ελλήνων βουλευτών 2024</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sentimentErgasia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ανάλυση συναισθήματος στο Reddit</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./metanastes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Θέσεις αριστεράς για μεταναστευτικό</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./strikes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Απεργιακές κινητοποιήσεις</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./spiti.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Εξέταση τιμών ακινήτων</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./aytokinhta.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Αξιολόγηση αυτοκινήτων</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kondratiev.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Κύματα Kondratiev</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SilurianHypothesis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Σιλούρια υπόθεση</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#παρουσίαση-δεδομένων" id="toc-παρουσίαση-δεδομένων" class="nav-link active" data-scroll-target="#παρουσίαση-δεδομένων"><span class="header-section-number">1</span> Παρουσίαση δεδομένων</a></li>
  <li><a href="#επιδράσεις-παραγόντων" id="toc-επιδράσεις-παραγόντων" class="nav-link" data-scroll-target="#επιδράσεις-παραγόντων"><span class="header-section-number">2</span> Επιδράσεις παραγόντων</a>
  <ul class="collapse">
  <li><a href="#το-είδος-των-εκλογών" id="toc-το-είδος-των-εκλογών" class="nav-link" data-scroll-target="#το-είδος-των-εκλογών"><span class="header-section-number">2.1</span> Το είδος των εκλογών</a></li>
  <li><a href="#η-εποχή" id="toc-η-εποχή" class="nav-link" data-scroll-target="#η-εποχή"><span class="header-section-number">2.2</span> Η εποχή</a></li>
  </ul></li>
  <li><a href="#πορεία-στο-χρόνο" id="toc-πορεία-στο-χρόνο" class="nav-link" data-scroll-target="#πορεία-στο-χρόνο"><span class="header-section-number">3</span> Πορεία στο χρόνο</a></li>
  <li><a href="#συσχετίσεις" id="toc-συσχετίσεις" class="nav-link" data-scroll-target="#συσχετίσεις"><span class="header-section-number">4</span> Συσχετίσεις</a>
  <ul class="collapse">
  <li><a href="#μεταξύ-αποχής-άκυρου-λευκού" id="toc-μεταξύ-αποχής-άκυρου-λευκού" class="nav-link" data-scroll-target="#μεταξύ-αποχής-άκυρου-λευκού"><span class="header-section-number">4.1</span> Μεταξύ αποχής-άκυρου-λευκού</a></li>
  <li><a href="#με-μεταβολή-πληθυσμού" id="toc-με-μεταβολή-πληθυσμού" class="nav-link" data-scroll-target="#με-μεταβολή-πληθυσμού"><span class="header-section-number">4.2</span> Με μεταβολή πληθυσμού</a></li>
  </ul></li>
  <li><a href="#προβλέψεις" id="toc-προβλέψεις" class="nav-link" data-scroll-target="#προβλέψεις"><span class="header-section-number">5</span> Προβλέψεις</a></li>
  <li><a href="#προτάσεις-για-περεταίρω-μελέτη" id="toc-προτάσεις-για-περεταίρω-μελέτη" class="nav-link" data-scroll-target="#προτάσεις-για-περεταίρω-μελέτη"><span class="header-section-number">6</span> Προτάσεις για περεταίρω μελέτη</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Αποχή στις εκλογές</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Κώστας Κούδας </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 15, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Πλησιάζουν οι αυτοδιοικητικές εκλογές του 2023 και διάφορα στόματα εκφράζουν μια απόγνωση για την έλλειψη επιλογών που να τα εκφράζουν. Στις πρόσφατες βουλευτικές εκλογές η αξιωματική αντιπολίτευση είχε μεγάλη πτώση, πιθανώς να απογοήτευσε αρκετούς και πλέον αυτοί να μην βρίσκουν κόμματα της αρεσκείας τους από τη γκάμα των διαθέσιμων επιλογών. Η αποχή φαίνεται να αναδεικνύεται σε ισχυρή πολιτική στάση και γι’ αυτό θα τη μελετήσουμε και μαζί της θα μελετήσουμε και τα άκυρα/λευκά ψηφοδέλτια, τα οποία μπορεί να αντανακλούν μια παρόμοια στάση απογοήτευσης με τις εκλογικές επιλογές.</p>
<section id="παρουσίαση-δεδομένων" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Παρουσίαση δεδομένων</h1>
<p>Η πρώτη επιλογή για την άντληση δεδομένων ήταν και η εύκολη, η Wikipedia. Δυστυχώς, ψάχνοντας στα επίσημα στοιχεία του κράτους βρέθηκαν πάρα πολλές αναντιστοιχίες. Επί παραδείγματι στις εκλογές του Ιανουαρίου του 1985 η <a href="https://shorturl.at/Nidpi">Wikipedia</a> δίνει ότι οι εγγεγραμμένοι ήταν 9’949’684, ενώ το <a href="https://shorturl.at/Loqpl">Υπουργείο Εσωτερικών</a> δίνει 9’900’403. Η Wikipedia, δηλαδή, δίνει 49’281 παραπάνω εγγεγραμμένους, αλλά, όσο μεγάλο και να φαίνεται αυτό το νούμερο, στην πραγματικότητα αυτό αντιστοιχεί στο 0.5% του πραγματικού πλήθους. Πιθανότατα η Wikipedia να άντλησε κάποια δεδομένα και κάποια ποσοστά και ακολούθως να εξήγαγε τα δεδομένα που της έλλειπαν μέσω υπολογισμών με ποσοστά. Οπότε μάλλον αυτή η απόκλιση που βλέπουμε αντικατοπτρίζει σφάλματα στρογγυλοποίησης.</p>
<p>Όπως και να ’χει, παρότι δεν μιλάμε για σοβαρές αναντιστοιχίες, έγινε προσπάθεια να ελαχιστοποιηθεί η Wikipedia ως πηγή στο παρόν άρθρο. Δυστυχώς όμως πολλοί σύνδεσμοι του Υπουργείου Εσωτερικών δεν λειτουργούσαν και για πολλές εκλογές δεν υπήρχαν καθόλου πηγές. Οπότε ο γράφων σε κάποιες περιπτώσεις στράφηκε σε άλλες πηγές, η επωνυμία των οποίων τού παρείχε περισσότερη εμπιστοσύνη για την αξιοπιστία των δεδομένων τους, και στις υπόλοιπες αρκέστηκε στη Wikipedia.</p>
<p>Ακριβώς αυτή η έλλειψη πηγών είναι που έκανε τις αυτοδιοικητικές εκλογές να απουσιάσουν εντελώς από την παρούσα μελέτη. Ο ενδιαφερόμενος αναγνώστης με πρόσβαση σε πηγές των αυτοδιοικητικών εκλογών, μπορεί να εμπλουτίσει το αρχείο με τα δεδομένα και να χρησιμοποιήσει λίγο-πολύ τον κώδικα που θα χρησιμοποιήσουμε, ώστε να κάνει τη δικιά του πληρέστερη μελέτη.</p>
<p>Τα δεδομένα παρατίθενται στον παρακάτω πίνακα και είναι διαθέσιμα στο αρχείο simetoxiN_EU.xlsx, που παρατίθεται κάτωθεν του πίνακα, και να το χρησιμοποιήσει κατά το δοκούν.</p>
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:200px; overflow-x: scroll; width:100%; ">
<table class="table table-striped caption-top">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: right; position: sticky; top: 0; background-color: #FFFFFF;">ETOS</th>
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;">MINAS</th>
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;">EPOXI</th>
<th data-quarto-table-cell-role="th" style="text-align: right; position: sticky; top: 0; background-color: #FFFFFF;">PSIFISAN</th>
<th data-quarto-table-cell-role="th" style="text-align: right; position: sticky; top: 0; background-color: #FFFFFF;">EGGEGRAMMENOI</th>
<th data-quarto-table-cell-role="th" style="text-align: right; position: sticky; top: 0; background-color: #FFFFFF;">AKIRA</th>
<th data-quarto-table-cell-role="th" style="text-align: right; position: sticky; top: 0; background-color: #FFFFFF;">AKIRA_p</th>
<th data-quarto-table-cell-role="th" style="text-align: right; position: sticky; top: 0; background-color: #FFFFFF;">LEFKA</th>
<th data-quarto-table-cell-role="th" style="text-align: right; position: sticky; top: 0; background-color: #FFFFFF;">LEFKA_p</th>
<th data-quarto-table-cell-role="th" style="text-align: right; position: sticky; top: 0; background-color: #FFFFFF;">AKIRO_LEFKO</th>
<th data-quarto-table-cell-role="th" style="text-align: right; position: sticky; top: 0; background-color: #FFFFFF;">AKIRO_LEFKO_p</th>
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;">EIDOS_EKLOGON</th>
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;">PIGI</th>
<th data-quarto-table-cell-role="th" style="text-align: left; position: sticky; top: 0; background-color: #FFFFFF;">SYNDESMOI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1977</td>
<td style="text-align: left;">NO</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">5193891</td>
<td style="text-align: right;">6403738</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">64120</td>
<td style="text-align: right;">0.0123453</td>
<td style="text-align: left;">bouleftikes</td>
<td style="text-align: left;">IMER</td>
<td style="text-align: left;">https://www.imerodromos.gr/ekloges-1974-shmera/</td>
</tr>
<tr class="even">
<td style="text-align: right;">1981</td>
<td style="text-align: left;">OK</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">5753478</td>
<td style="text-align: right;">7059778</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">82421</td>
<td style="text-align: right;">0.0143254</td>
<td style="text-align: left;">bouleftikes</td>
<td style="text-align: left;">IMER</td>
<td style="text-align: left;">https://www.imerodromos.gr/ekloges-1974-shmera/</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1981</td>
<td style="text-align: left;">OK</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">5752349</td>
<td style="text-align: right;">7329409</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">74688</td>
<td style="text-align: right;">0.0129839</td>
<td style="text-align: left;">EU</td>
<td style="text-align: left;">WIKI</td>
<td style="text-align: left;">https://el.wikipedia.org/wiki/%CE%9A%CE%B1%CF%84%CE%B7%CE%B3%CE%BF%CF%81%CE%AF%CE%B1:%CE%95%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AD%CF%82_%CE%B2%CE%BF%CF%85%CE%BB%CE%B5%CF%85%CF%84%CE%B9%CE%BA%CE%AD%CF%82_%CE%B5%CE%BA%CE%BB%CE%BF%CE%B3%CE%AD%CF%82</td>
</tr>
<tr class="even">
<td style="text-align: right;">1984</td>
<td style="text-align: left;">IN</td>
<td style="text-align: left;">K</td>
<td style="text-align: right;">6011816</td>
<td style="text-align: right;">7790309</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">55756</td>
<td style="text-align: right;">0.0092744</td>
<td style="text-align: left;">EU</td>
<td style="text-align: left;">WIKI</td>
<td style="text-align: left;">https://el.wikipedia.org/wiki/%CE%9A%CE%B1%CF%84%CE%B7%CE%B3%CE%BF%CF%81%CE%AF%CE%B1:%CE%95%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AD%CF%82_%CE%B2%CE%BF%CF%85%CE%BB%CE%B5%CF%85%CF%84%CE%B9%CE%BA%CE%AD%CF%82_%CE%B5%CE%BA%CE%BB%CE%BF%CE%B3%CE%AD%CF%82</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1985</td>
<td style="text-align: left;">IN</td>
<td style="text-align: left;">K</td>
<td style="text-align: right;">6422466</td>
<td style="text-align: right;">8008647</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">57372</td>
<td style="text-align: right;">0.0089330</td>
<td style="text-align: left;">bouleftikes</td>
<td style="text-align: left;">IMER</td>
<td style="text-align: left;">https://www.imerodromos.gr/ekloges-1974-shmera/</td>
</tr>
<tr class="even">
<td style="text-align: right;">1989</td>
<td style="text-align: left;">IN</td>
<td style="text-align: left;">K</td>
<td style="text-align: right;">6704752</td>
<td style="text-align: right;">8377904</td>
<td style="text-align: right;">104891</td>
<td style="text-align: right;">0.0156443</td>
<td style="text-align: right;">18620</td>
<td style="text-align: right;">0.0027771</td>
<td style="text-align: right;">123511</td>
<td style="text-align: right;">0.0184214</td>
<td style="text-align: left;">EU</td>
<td style="text-align: left;">WIKI</td>
<td style="text-align: left;">https://el.wikipedia.org/wiki/%CE%9A%CE%B1%CF%84%CE%B7%CE%B3%CE%BF%CF%81%CE%AF%CE%B1:%CE%95%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AD%CF%82_%CE%B2%CE%BF%CF%85%CE%BB%CE%B5%CF%85%CF%84%CE%B9%CE%BA%CE%AD%CF%82_%CE%B5%CE%BA%CE%BB%CE%BF%CE%B3%CE%AD%CF%82</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1989</td>
<td style="text-align: left;">NO</td>
<td style="text-align: left;">K</td>
<td style="text-align: right;">6669481</td>
<td style="text-align: right;">8379435</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">147918</td>
<td style="text-align: right;">0.0221783</td>
<td style="text-align: left;">bouleftikes</td>
<td style="text-align: left;">IMER</td>
<td style="text-align: left;">https://www.imerodromos.gr/ekloges-1974-shmera/</td>
</tr>
<tr class="even">
<td style="text-align: right;">1989</td>
<td style="text-align: left;">NO</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">6798159</td>
<td style="text-align: right;">8637323</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">101675</td>
<td style="text-align: right;">0.0149563</td>
<td style="text-align: left;">bouleftikes</td>
<td style="text-align: left;">IMER</td>
<td style="text-align: left;">https://www.imerodromos.gr/ekloges-1974-shmera/</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1990</td>
<td style="text-align: left;">AR</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">6698591</td>
<td style="text-align: right;">8453685</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">112551</td>
<td style="text-align: right;">0.0168022</td>
<td style="text-align: left;">bouleftikes</td>
<td style="text-align: left;">IMER</td>
<td style="text-align: left;">https://www.imerodromos.gr/ekloges-1974-shmera/</td>
</tr>
<tr class="even">
<td style="text-align: right;">1993</td>
<td style="text-align: left;">OK</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">7019925</td>
<td style="text-align: right;">8861833</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">119614</td>
<td style="text-align: right;">0.0170392</td>
<td style="text-align: left;">bouleftikes</td>
<td style="text-align: left;">IMER</td>
<td style="text-align: left;">https://www.imerodromos.gr/ekloges-1974-shmera/</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1994</td>
<td style="text-align: left;">IN</td>
<td style="text-align: left;">K</td>
<td style="text-align: right;">6803884</td>
<td style="text-align: right;">9550596</td>
<td style="text-align: right;">144126</td>
<td style="text-align: right;">0.0211829</td>
<td style="text-align: right;">127167</td>
<td style="text-align: right;">0.0186904</td>
<td style="text-align: right;">271293</td>
<td style="text-align: right;">0.0398733</td>
<td style="text-align: left;">EU</td>
<td style="text-align: left;">WIKI</td>
<td style="text-align: left;">https://el.wikipedia.org/wiki/%CE%9A%CE%B1%CF%84%CE%B7%CE%B3%CE%BF%CF%81%CE%AF%CE%B1:%CE%95%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AD%CF%82_%CE%B2%CE%BF%CF%85%CE%BB%CE%B5%CF%85%CF%84%CE%B9%CE%BA%CE%AD%CF%82_%CE%B5%CE%BA%CE%BB%CE%BF%CE%B3%CE%AD%CF%82</td>
</tr>
<tr class="even">
<td style="text-align: right;">1996</td>
<td style="text-align: left;">SE</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">6978656</td>
<td style="text-align: right;">9140742</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">198607</td>
<td style="text-align: right;">0.0284592</td>
<td style="text-align: left;">bouleftikes</td>
<td style="text-align: left;">MOUR</td>
<td style="text-align: left;">http://www.physics.ntua.gr/mourmouras/agxivasihn/ekloges_1999_2019.html</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1999</td>
<td style="text-align: left;">IN</td>
<td style="text-align: left;">K</td>
<td style="text-align: right;">6712684</td>
<td style="text-align: right;">9555326</td>
<td style="text-align: right;">150501</td>
<td style="text-align: right;">0.0224204</td>
<td style="text-align: right;">133487</td>
<td style="text-align: right;">0.0198858</td>
<td style="text-align: right;">283988</td>
<td style="text-align: right;">0.0423062</td>
<td style="text-align: left;">EU</td>
<td style="text-align: left;">MOUR</td>
<td style="text-align: left;">http://www.physics.ntua.gr/mourmouras/agxivasihn/ekloges_1999_2019.html</td>
</tr>
<tr class="even">
<td style="text-align: right;">2000</td>
<td style="text-align: left;">AR</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">7026527</td>
<td style="text-align: right;">9372541</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">158516</td>
<td style="text-align: right;">0.0225597</td>
<td style="text-align: left;">bouleftikes</td>
<td style="text-align: left;">MOUR</td>
<td style="text-align: left;">http://www.physics.ntua.gr/mourmouras/agxivasihn/ekloges_1999_2019.html</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2004</td>
<td style="text-align: left;">MR</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">7573368</td>
<td style="text-align: right;">9899472</td>
<td style="text-align: right;">123713</td>
<td style="text-align: right;">0.0163353</td>
<td style="text-align: right;">43036</td>
<td style="text-align: right;">0.0056825</td>
<td style="text-align: right;">166749</td>
<td style="text-align: right;">0.0220178</td>
<td style="text-align: left;">bouleftikes</td>
<td style="text-align: left;">Y_E</td>
<td style="text-align: left;">https://ekloges.ypes.gr/</td>
</tr>
<tr class="even">
<td style="text-align: right;">2004</td>
<td style="text-align: left;">IN</td>
<td style="text-align: left;">K</td>
<td style="text-align: right;">6283637</td>
<td style="text-align: right;">9938863</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">161005</td>
<td style="text-align: right;">0.0256229</td>
<td style="text-align: left;">EU</td>
<td style="text-align: left;">MOUR</td>
<td style="text-align: left;">http://www.physics.ntua.gr/mourmouras/agxivasihn/ekloges_1999_2019.html</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2007</td>
<td style="text-align: left;">SE</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">7355026</td>
<td style="text-align: right;">9918917</td>
<td style="text-align: right;">148850</td>
<td style="text-align: right;">0.0202379</td>
<td style="text-align: right;">47170</td>
<td style="text-align: right;">0.0064133</td>
<td style="text-align: right;">196020</td>
<td style="text-align: right;">0.0266512</td>
<td style="text-align: left;">bouleftikes</td>
<td style="text-align: left;">Y_E</td>
<td style="text-align: left;">https://ekloges.ypes.gr/</td>
</tr>
<tr class="even">
<td style="text-align: right;">2009</td>
<td style="text-align: left;">IN</td>
<td style="text-align: left;">Κ</td>
<td style="text-align: right;">5261749</td>
<td style="text-align: right;">10014795</td>
<td style="text-align: right;">72919</td>
<td style="text-align: right;">0.0138583</td>
<td style="text-align: right;">60934</td>
<td style="text-align: right;">0.0115806</td>
<td style="text-align: right;">133853</td>
<td style="text-align: right;">0.0254389</td>
<td style="text-align: left;">EU</td>
<td style="text-align: left;">Y_E</td>
<td style="text-align: left;">https://ekloges.ypes.gr/</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2009</td>
<td style="text-align: left;">OK</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">7044606</td>
<td style="text-align: right;">9929065</td>
<td style="text-align: right;">142916</td>
<td style="text-align: right;">0.0202873</td>
<td style="text-align: right;">43269</td>
<td style="text-align: right;">0.0061421</td>
<td style="text-align: right;">186185</td>
<td style="text-align: right;">0.0264294</td>
<td style="text-align: left;">bouleftikes</td>
<td style="text-align: left;">Y_E</td>
<td style="text-align: left;">https://ekloges.ypes.gr/</td>
</tr>
<tr class="even">
<td style="text-align: right;">2012</td>
<td style="text-align: left;">MA</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">6476818</td>
<td style="text-align: right;">9945859</td>
<td style="text-align: right;">114769</td>
<td style="text-align: right;">0.0177200</td>
<td style="text-align: right;">37913</td>
<td style="text-align: right;">0.0058536</td>
<td style="text-align: right;">152682</td>
<td style="text-align: right;">0.0235736</td>
<td style="text-align: left;">bouleftikes</td>
<td style="text-align: left;">Y_E</td>
<td style="text-align: left;">https://ekloges.ypes.gr/</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2012</td>
<td style="text-align: left;">IN</td>
<td style="text-align: left;">K</td>
<td style="text-align: right;">6216798</td>
<td style="text-align: right;">9947876</td>
<td style="text-align: right;">35961</td>
<td style="text-align: right;">0.0057845</td>
<td style="text-align: right;">25373</td>
<td style="text-align: right;">0.0040814</td>
<td style="text-align: right;">61334</td>
<td style="text-align: right;">0.0098659</td>
<td style="text-align: left;">bouleftikes</td>
<td style="text-align: left;">Y_E</td>
<td style="text-align: left;">https://ekloges.ypes.gr/</td>
</tr>
<tr class="even">
<td style="text-align: right;">2014</td>
<td style="text-align: left;">MA</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">5941636</td>
<td style="text-align: right;">10013834</td>
<td style="text-align: right;">157094</td>
<td style="text-align: right;">0.0264395</td>
<td style="text-align: right;">68557</td>
<td style="text-align: right;">0.0115384</td>
<td style="text-align: right;">225651</td>
<td style="text-align: right;">0.0379779</td>
<td style="text-align: left;">EU</td>
<td style="text-align: left;">Y_E</td>
<td style="text-align: left;">https://ekloges.ypes.gr/</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2015</td>
<td style="text-align: left;">IN</td>
<td style="text-align: left;">K</td>
<td style="text-align: right;">6330356</td>
<td style="text-align: right;">9900403</td>
<td style="text-align: right;">114654</td>
<td style="text-align: right;">0.0181118</td>
<td style="text-align: right;">34830</td>
<td style="text-align: right;">0.0055021</td>
<td style="text-align: right;">149484</td>
<td style="text-align: right;">0.0236138</td>
<td style="text-align: left;">bouleftikes</td>
<td style="text-align: left;">Y_E</td>
<td style="text-align: left;">https://ekloges.ypes.gr/</td>
</tr>
<tr class="even">
<td style="text-align: right;">2015</td>
<td style="text-align: left;">SE</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">5567930</td>
<td style="text-align: right;">9913609</td>
<td style="text-align: right;">69884</td>
<td style="text-align: right;">0.0125512</td>
<td style="text-align: right;">64670</td>
<td style="text-align: right;">0.0116147</td>
<td style="text-align: right;">134554</td>
<td style="text-align: right;">0.0241659</td>
<td style="text-align: left;">bouleftikes</td>
<td style="text-align: left;">Y_E</td>
<td style="text-align: left;">https://ekloges.ypes.gr/</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2019</td>
<td style="text-align: left;">MA</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">5920355</td>
<td style="text-align: right;">10088325</td>
<td style="text-align: right;">173781</td>
<td style="text-align: right;">0.0293531</td>
<td style="text-align: right;">90455</td>
<td style="text-align: right;">0.0152786</td>
<td style="text-align: right;">264236</td>
<td style="text-align: right;">0.0446318</td>
<td style="text-align: left;">EU</td>
<td style="text-align: left;">Y_E</td>
<td style="text-align: left;">https://ekloges.ypes.gr/</td>
</tr>
<tr class="even">
<td style="text-align: right;">2019</td>
<td style="text-align: left;">IL</td>
<td style="text-align: left;">K</td>
<td style="text-align: right;">5769644</td>
<td style="text-align: right;">9984934</td>
<td style="text-align: right;">77477</td>
<td style="text-align: right;">0.0134284</td>
<td style="text-align: right;">77477</td>
<td style="text-align: right;">0.0134284</td>
<td style="text-align: right;">154954</td>
<td style="text-align: right;">0.0268568</td>
<td style="text-align: left;">bouleftikes</td>
<td style="text-align: left;">Y_E</td>
<td style="text-align: left;">https://ekloges.ypes.gr/</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2023</td>
<td style="text-align: left;">MA</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">6061040</td>
<td style="text-align: right;">9813595</td>
<td style="text-align: right;">123318</td>
<td style="text-align: right;">0.0203460</td>
<td style="text-align: right;">34959</td>
<td style="text-align: right;">0.0057678</td>
<td style="text-align: right;">158277</td>
<td style="text-align: right;">0.0261138</td>
<td style="text-align: left;">bouleftikes</td>
<td style="text-align: left;">Y_E</td>
<td style="text-align: left;">https://ekloges.ypes.gr/</td>
</tr>
<tr class="even">
<td style="text-align: right;">2023</td>
<td style="text-align: left;">IN</td>
<td style="text-align: left;">K</td>
<td style="text-align: right;">5273699</td>
<td style="text-align: right;">9813595</td>
<td style="text-align: right;">32219</td>
<td style="text-align: right;">0.0061094</td>
<td style="text-align: right;">26273</td>
<td style="text-align: right;">0.0049819</td>
<td style="text-align: right;">58492</td>
<td style="text-align: right;">0.0110913</td>
<td style="text-align: left;">bouleftikes</td>
<td style="text-align: left;">Y_E</td>
<td style="text-align: left;">https://ekloges.ypes.gr/</td>
</tr>
</tbody>
</table>
</div>
<p>Στον παραπάνω πίνακα παρουσιάζεται:</p>
<ul>
<li><p>το έτος που έγιναν οι εκλογές (στήλη <code>ETOS</code>),</p></li>
<li><p>ο μήνας που έγιναν οι εκλογές (στήλη <code>MINAS</code>),</p></li>
<li><p>το πόσα άτομα ψήφισαν (στήλη <code>PSIFISAN</code>),</p></li>
<li><p>το πόσα άτομα ήταν εγγεγραμμένα στους εκλογικούς καταλόγους (στήλη <code>EGGEGRAMMENOI</code>),</p></li>
<li><p>το πόσα ήταν τα άκυρα (στήλη <code>AKIRA</code>) και το ποσοστό τους (στήλη <code>AKIRA_p</code>),</p></li>
<li><p>το πόσα ήταν τα λευκά (στήλη <code>LEFKA</code>) και το ποσοστό τους (στήλη <code>LEFKA_p</code>),</p></li>
<li><p>το πόσα ήταν τα άκυρα μαζί με τα λευκά (στήλη <code>AKIRO_LEFKO</code>) και το ποσοστό τους (`AKIRO_LEFKO_p``),</p></li>
<li><p>το αν ήταν βουλευτικές εκλογές ή ευρωεκλογές (στήλη <code>EIDOS_EKLOGON</code>), η πηγή που αντλήθηκαν τα δεδομένα (στήλη <code>PIGI</code>) και ο αντίστοιχος σύνδεσμος (στήλη <code>SYNDESMOI</code>).</p></li>
</ul>
</section>
<section id="επιδράσεις-παραγόντων" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Επιδράσεις παραγόντων</h1>
<section id="το-είδος-των-εκλογών" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="το-είδος-των-εκλογών"><span class="header-section-number">2.1</span> Το είδος των εκλογών</h2>
<p>Φλερτάροντας ο γράφων με τον ευρωσκεπτικιστικό χώρο είχε πάντα την αίσθηση ότι οι ευρωεκλογές αντιμετωπίζονται απαξιωτικά από τους περισσότερους ανθρώπους, έναντι τουλάχιστον των βουλευτικών, όπερ θα αντανακλόταν και στο μέγεθος της αποχής. Είναι όμως έτσι ή απλά έκρινε εξ ιδίων τα αλλότρια; Αυτό θα μελετήσουμε τώρα.</p>
<p>Πώς θα καταφέρουμε να ελέγξουμε αν επιδρά στο μέγεθος της αποχής ο παράγοντας «είδος εκλογών»; Αρχικά θα υποθέσουμε ότι αυτός δεν επιδρά, δηλαδή ότι η αποχή δεν έχει ουσιαστικές διαφορές ανάμεσα στις ευρωεκλογές και τις βουλευτικές εκλογές (μηδενική υπόθεση). Ακολούθως θα εκτελέσουμε τον έλεγχο Kruskal-Wallis, ώστε να δούμε πόσο πιθανό όμως είναι να τύχουμε τέτοιες διαφορές στα ποσοστά αποχής μεταξύ ευρωεκλογών και βουλευτικών εκλογών, δεδομένης αυτής της υπόθεσης που κάναμε. Αν μας βγει ότι τελικά αυτές οι διαφοροποιήσεις είναι εντελώς απίθανο να συμβούν (δηλαδή έχουν πιθανότητα μικρότερη του 5%), σημαίνει ότι δεν μπορούμε να δεχτούμε την υπόθεση ότι ο παράγοντας «είδος εκλογών» δεν επιδρά.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  APOXI_p by EIDOS_EKLOGON
Kruskal-Wallis chi-squared = 0.92015, df = 1, p-value = 0.3374</code></pre>
</div>
</div>
<p>Εκτελώντας τον εν λόγω έλεγχο προκύπτει p-τιμή το 0.3374, δηλαδή μπορούμε να είμαστε 33.74% σίγουροι ότι θα έχουμε τέτοιες διαφοροποιήσεις ανάμεσα στις ευρωεκλογές και στις βουλευτικές εκλογές, ακόμα κι αν ο παράγοντας «είδος εκλογών» δεν έχει καμία επίδραση. Αυτό όμως πολύ παραπάνω από το 5% που θα θέλαμε για να θεωρούμε κάτι πραγματικά σπάνιο, οπότε ο παράγοντας «είδος εκλογών» είναι αθώος μέχρι αποδείξεως του εναντίου.</p>
<p>Τι γίνεται όμως με το λευκό και το άκυρο; Εκεί παίζει ρόλο το είδος των εκλογών;</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  AKIRA_p by EIDOS_EKLOGON
Kruskal-Wallis chi-squared = 3.8118, df = 1, p-value = 0.05089</code></pre>
</div>
</div>
<p>Όσον αφορά τα άκυρα, βλέπουμε ότι η p-τιμή είναι 0.7585. Αυτό σημαίνει ότι ούτε τα άκυρα έχουμε ενδείξεις ότι επηρεάζονται από το είδος των εκλογών. Τι γενεται όμως με τα λευκά;</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  LEFKA_p by EIDOS_EKLOGON
Kruskal-Wallis chi-squared = 3.0118, df = 1, p-value = 0.08266</code></pre>
</div>
</div>
<p>Στην περίπτωση των λευκών η p-τιμή είναι 0.08149, όπερ ξεφεύγει εμφανώς (αλλά όχι τόσο όσο πριν) από αυτό που θεωρούμε σπάνιο. Ομοίως και ο συνδυασμός άκυρων-λευκών που έχει p-τιμή το 0.1213, όπως βλέπουμε ακολούθως.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  AKIRO_LEFKO_p by EIDOS_EKLOGON
Kruskal-Wallis chi-squared = 2.4011, df = 1, p-value = 0.1213</code></pre>
</div>
</div>
<p>Παραταύτα, αν θέλουμε να είμαστε τυπικοί, η p-τιμή των ακύρων το φράγμα του 5% δεν το ξεπερνάει, οπότε μπορούμε να θεωρήσουμε ότι δεν είναι όσο σπάνια περίπτωση θα θέλαμε. Αυτό και θα υιοθετήσουμε σαν στάση στην παρούσα έρευνα, οπότε δεν θα κάνουμε ξεχωριστή μελέτη στις βουλευτικές εκλογές και στις ευρωεκλογές. Ο αναγνώστης που δεν καλύπτεται από την τυπολατρία του γράφοντος μπορεί να κάνει τη σχετική έρευνα χρησιμοποιώντας τα στοιχεία του κώδικα που έχουν απενεργοποιηθεί.</p>
</section>
<section id="η-εποχή" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="η-εποχή"><span class="header-section-number">2.2</span> Η εποχή</h2>
<p>Μιας και εξετάσαμε την επίδραση ενός παράγοντα, ας εξετάσουμε και την επίδραση ενός άλλου. Στις προηγούμενες εκλογές, τις βουλευτικές του Ιουνίου 2023, ακουγόταν από διάφορα στόματα η ανησυχία ότι πολλοί εργαζόμενοι δεν θα μπορούν να παρευρεθούν στις κάλπες λόγω της εργασίας τους σε άλλα μέρη από τον τόπο καταγωγής τους. Πολλοί νέοι, για παράδειγμα, πηγαίνουν και δουλεύουν για το καλοκαίρι σε διάφορα νησιά, πράγμα που θα τους εμπόδιζε στις εκλογικές τους υποχρεώσεις. Ήταν βάσιμη αυτή η ανησυχία;</p>
<p>Ουσιαστικά ενδιαφερόμαστε περί του αν επιδρά στο μέγεθος της αποχής το γεγονός ότι οι εκλογές τελούνται το καλοκαίρι, το φθινόπωρο, το χειμώνα ή την άνοιξη. Θα το εξετάσουμε κάνοντας πάλι έλεγχο Kruskal-Wallis.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  APOXI_p by EPOXI
Kruskal-Wallis chi-squared = 5.3267, df = 3, p-value = 0.1494</code></pre>
</div>
</div>
<p>Τοιαύτη περιπτώσει βρίσκουμε p-τιμή 0.1494, επομένως δεν έχουμε επαρκή στοιχεία για να καταλογίσουμε ευθύνες στον παράγοντα «εποχή» όσον αφορά το μέγεθος της αποχής. Και αυτός ο παράγοντας είναι αθώος μέχρι αποδείξεως του εναντίου.</p>
</section>
</section>
<section id="πορεία-στο-χρόνο" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Πορεία στο χρόνο</h1>
<p>Στην ενότητα αυτή θα εξετάσουμε την πορεία στον χρόνο των στάσεων «απέχω», «ρίχνω άκυρο» και «ρίχνω λευκό».</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apoxi_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Παρατηρώντας το χρονοδιάγραμμα του ποσοστού της αποχής παρατηρούμε μιαν αυξητική στάση. Αυτό επιβεβαιώνεται και από τον συντελεστή μονοτονικής συσχέτισης Spearman, ο οποίος έχει τιμή 0.900371, όπερ δηλώνει πολύ ισχυρή αυξητική τάση:</p>
<p>Όσον αφορά τα άκυρα και τα λευκά δεν φαίνεται εκ πρώτης όψεως να υπάρχει τέτοια τάση. Οι συντελεστές Spearman δηλώνουν αμελητέα πτωτική τάση (-0.1431744 και -0.0708492). Τα χρονοδιαγράμματά τους επίσης δεν φαίνεται να διαφωνούν με όσα λέμε τώρα.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>( <span class="at">mfrow=</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>) )</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(simetoxiN_EU<span class="sc">$</span>ETOS, akira_p, <span class="at">type =</span> <span class="st">"l"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(simetoxiN_EU<span class="sc">$</span>ETOS, lefka_p, <span class="at">type =</span> <span class="st">"l"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apoxi_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Στην πραγματικότητα όμως τα δεδομένα μας είναι πολύ φτωχά όσον αφορά τα άκυρα και τα λευκά. Οι περισσότερες πηγές τα παρουσίαζαν μαζί και λίγες μόνο έδιναν πόσο ήταν το κάθε ένα ξεχωριστά.</p>
<p>Έτσι, μελετώντας την περίπτωση των άκυρων και των λευκών μαζί έχουμε συντελεστή Spearman 0.5045915, κάτι που υποδηλώνει ισχυρή αυξητική τάση. Αυτό με λίγη προσοχή φαίνεται να επιβεβαιώνεται και από το χρονοδιάγραμμα.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apoxi_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="συσχετίσεις" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Συσχετίσεις</h1>
<section id="μεταξύ-αποχής-άκυρου-λευκού" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="μεταξύ-αποχής-άκυρου-λευκού"><span class="header-section-number">4.1</span> Μεταξύ αποχής-άκυρου-λευκού</h2>
<p>Είδαμε προηγουμένως ότι τόσο η αποχή, όσο και τα άκυρα/λευκά ακολουθούν μιαν αυξητική τάση. Μήπως αυτό σημαίνει ότι σχετίζονται μεταξύ τους; Δεν μιλάμε για συσχέτιση αιτίου-αιτιατού, αλλά για κοινή αντανάκλαση μιας κοινωνικής τάσης. Μήπως, δηλαδή, οι κοινές αυξητικές στάσεις υποδηλώνουν την ύπαρξη μιας κατάστασης απαξίωσης των πολιτικών κομμάτων στην Ελλάδα; Αυτό θα εξετάσουμε τώρα.</p>
<p>Κάνοντας το διάγραμμα διασποράς ακύρων-αποχής μαζί με την ευθεία γραμμικής παλινδρόμησης παρατηρούμε ότι όσο μεγαλώνει η αποχή, τόσο λιγοστεύουν τα άκυρα.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apoxi_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Η δε ευθεία γραμμικής παλινδρόμησης φαίνεται να περιγράφει σχετικά καλά τα δεδομένα μας, αφού το τυπικό σφάλμα εκτίμησης προέκυψε 0.006401.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = akira_p ~ apoxi_p)

Residuals:
       Min         1Q     Median         3Q        Max 
-0.0113083 -0.0033265  0.0004527  0.0027212  0.0129530 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)  0.023913   0.007179   3.331  0.00495 **
apoxi_p     -0.018186   0.019808  -0.918  0.37412   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.006401 on 14 degrees of freedom
  (12 observations deleted due to missingness)
Multiple R-squared:  0.05679,   Adjusted R-squared:  -0.01059 
F-statistic: 0.8429 on 1 and 14 DF,  p-value: 0.3741</code></pre>
</div>
</div>
<p>Αυτό σημαίνει ότι σχεδόν όλα τα πραγματικά ποσοστά των άκυρων διαφέρουν από τα προβλεπόμενα της ευθείας γραμμικής παλινδρόμησης κατά ±3·0.6401=±1.9203 ποσοστιαίες μονάδες.</p>
<p>Από την άλλη ο συντελεστής Pearson υποδηλώνει ασθενή γραμμική συσχέτιση, αφού είναι -0.2383006. Και πάλι όμως δείχνει μια πτωτική τάση, κάτι που επιβεβαιώνει και ο συντελεστής μονοτονικής συσχέτισης Spearman (-0.2852941). Μήπως αυτό σημαίνει ότι οι απογοητευμένοι από τα πολιτικά κόμματα αποτελούν μια σταθερή λίγο-πολύ «δεξαμενή», όπου ένα μέρος της επιλέγει το άκυρο κι ένα άλλο μέρος της επιλέγει την αποχή; Αυτό θα σήμαινε ότι αν μεγαλώσει το ένα μέρος, τότε θα μικρύνει το άλλο, κι έτσι θα ερμηνευόταν αυτό που παρατηρούμε.</p>
<p>Συσχετίζοντας τα λευκά με την αποχή παρατηρούμε μια σχεδόν ανεπαίσθητη αυξητική τάση. Η ευθεία γραμμικής παλινδρόμησης δείχνει ότι όσο η αποχή αυξάνεται, τόσο αυξάνεται και το ποσοστό των λευκών (τυπικό σφάλμα εκτίμησης 0.00543).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apoxi_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = lefka_p ~ apoxi_p)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.005630 -0.003903 -0.002024  0.002011  0.011217 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept) 0.005169   0.006090   0.849    0.410
apoxi_p     0.011767   0.016803   0.700    0.495

Residual standard error: 0.00543 on 14 degrees of freedom
  (12 observations deleted due to missingness)
Multiple R-squared:  0.03385,   Adjusted R-squared:  -0.03517 
F-statistic: 0.4904 on 1 and 14 DF,  p-value: 0.4952</code></pre>
</div>
</div>
<p>Η αλήθεια είναι όμως πως ο συντελεστής Pearson (0.1839712) δείχνει ακόμα ασθενέστερη γραμμική συσχέτιση σε σύγκριση με αυτή που είδαμε στην περίπτωση ακύρου-αποχής. Όμως, τόσο αυτός, όσο και ο συντελεστής Speaman (0.2147059) επιβεβαιώνουν την ύπαρξη ασθενούς έστω αυξητικής τάσης.</p>
<p>Έτσι, όσον αφορά τα λευκά-αποχή η θεωρία της «δεξαμενής» δεν φαίνεται να ισχύει. Εδώ φαίνεται να ισχύει η θεωρία που τα θέλει να αντικατοπτρίζουν μια κοινή απογοήτευση της κοινωνίας. Ίσως μια αύξηση/μείωση της κοινωνικής απογοήτευσης με τα πολιτικά κόμματα να επιφέρει και μιαν αύξηση/μείωση της απαξίωσης της εκλογικής διαδικασίας. Όπου αυτή η αύξηση/μείωση της απαξίωσης της εκλογικής διαδικασίας αντανακλάται:</p>
<ul>
<li><p>στην αύξηση/μείωση της απαξίωσης της εκλογικής διαδικασίας με τον «συστιμικό» τρόπο (λευκό),</p></li>
<li><p>στην αύξηση/μείωση της απαξίωσης της εκλογικής διαδικασίας με τον «αντισυστιμικό» τρόπο (αποχή).</p></li>
</ul>
<p>Θεωρώντας τα άκυρα και τα λευκά ως μία επιλογή (αν και ίσως να μην είναι) βλέπουμε και πάλι μιαν αυξητική τάση τους, όσο μεγαλώνει και η αποχή.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apoxi_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = akiro_lefko_p ~ apoxi_p)

Residuals:
       Min         1Q     Median         3Q        Max 
-0.0181719 -0.0042772 -0.0009465  0.0035050  0.0196823 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept) 0.010662   0.005832   1.828   0.0790 .
apoxi_p     0.040209   0.018656   2.155   0.0406 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.009197 on 26 degrees of freedom
Multiple R-squared:  0.1516,    Adjusted R-squared:  0.119 
F-statistic: 4.645 on 1 and 26 DF,  p-value: 0.04057</code></pre>
</div>
</div>
<p>Στην περίπτωση αυτή ο συντελεστής Pearson (0.3893421) δίνει μεγαλύτερη γραμμική συσχέτιση από αυτή που βλέπαμε προηγουμένως. Πλέον αυτή είναι μέτρια προς ισχυρή. Ο δε Spearman (0.5101259) αναφέρει την ύπαρξη ισχυρής αυξητικής τάσης.</p>
<p>Τέλος, μας μένει η συσχέτιση ακύρων και λευκών.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apoxi_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = lefka_p ~ akira_p)

Residuals:
       Min         1Q     Median         3Q        Max 
-0.0058280 -0.0040081 -0.0009782  0.0038101  0.0086310 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept) 0.002488   0.003674   0.677   0.5093  
akira_p     0.391028   0.198130   1.974   0.0685 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.004886 on 14 degrees of freedom
  (12 observations deleted due to missingness)
Multiple R-squared:  0.2177,    Adjusted R-squared:  0.1618 
F-statistic: 3.895 on 1 and 14 DF,  p-value: 0.0685</code></pre>
</div>
</div>
<p>Ο συντελεστής Pearson (0.4665415) υποδηλώνει μιαν ισχυρή γραμμική συσχέτιση μεταξύ των ακύρων και των λευκών. Ο Spearman (0.5029412) αναφέρει κι αυτός την ισχυρή αυξητική τάση που βλέπουμε και από το διάγραμμα διασποράς.</p>
<p>Τελικά η αρνητική συσχέτιση ακύρων αποχής φαντάζει μια παραφωνία μετά απ’ όλη αυτή τη συζήτηση. Θα μπορούσε κάποιος να την αγνοήσει και να την ανάγει στα σφάλματα λόγω του περιορισμένου αριθμού δεδομένων. Αυτό είναι μια δουλειά που μπορεί να συνεχίσει ο αναγνώστης. Εμείς την παρούσα ενότητα την τερματίζουμε εδώ.</p>
</section>
<section id="με-μεταβολή-πληθυσμού" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="με-μεταβολή-πληθυσμού"><span class="header-section-number">4.2</span> Με μεταβολή πληθυσμού</h2>
<p>Στην ενότητα αυτή θα εξετάσουμε το ποσοστό της αποχής-ακύρων-λευκών σε σχέση με τη μεταβολή του πληθυσμού.</p>
<p>Αντλήσαμε δεδομένα από τη σελίδα <a href="https://data.worldbank.org/indicator/SP.POP.TOTL?end=2022&amp;locations=GR&amp;start=1960&amp;view=chart">The World Bank</a> για τον πληθυσμό της Ελλάδας στα έτη των εκλογών. Προφανώς τις ημέρες των εκλογών ο πληθυσμός δεν θα ήταν ακριβώς αυτός που μας δίνεται, αλλά ας χαρίσουμε στον εαυτό μας λίγη μικρή ανακρίβεια ελλείψει καλύτερων στοιχείων.</p>
<p>Στο παρακάτω διάγραμμα διασποράς ο οριζόντιος άξονας απεικονίζει τη μεταβολή του ελληνικού πληθυσμού από τη μία εκλογική περίοδο στην άλλη. Είναι ιδιαίτερα ενδιαφέρον το ότι είναι τόσο εμφανής η πτωτική τάση της αποχής. Όσο μεγαλύτερη αύξηση πληθυσμού έχουμε, τόσο μικραίνει η αποχή.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apoxi_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>O συντελεστής Spearman (-0.6038682) επιβεβαιώνει την ύπαρξη ισχυρής πτωτικής τάσης.</p>
<p>Έχει ακόμα περισσότερο ενδιαφέρον να παρατηρήσουμε ότι όταν έχουμε αρνητική μεταβολή του πληθυσμού η αποχή είναι μεγαλύτερη από όταν έχουμε θετική μεταβολή του πληθυσμού. Δηλαδή όταν αυτός μειώνεται, η αποχή είναι μεγαλύτερη από όταν αυτός αυξάνεται. Την οπτική αυτή διαπίστωση την επιβεβαιώνει κι ο έλεγχος Kruskal-Wallis, ο οποίος εξάγει p-τιμή 0.04448.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  APOXI_p by THETIKI_METABOLI
Kruskal-Wallis chi-squared = 4.0381, df = 1, p-value = 0.04448</code></pre>
</div>
</div>
<p>Αυτό σημαίνει ότι αν ο παράγοντας «αύξηση ή μείωση πληθυσμού» δεν επιδρούσε στο μέγεθος της αποχής, τότε το να τύχουμε αυτά τα αποτελέσματα που βλέπουμε θα ήταν κάτι εντελώς απίθανο (0.45% πιθανό).</p>
<p>Έτσι όπως φαίνεται, η αποχή πρέπει να είναι η εκδήλωση ενός παράγοντα που συνεπιφέρει και τη μείωση του πληθυσμού. Θα μπορούσαμε να πούμε ότι π.χ. η απογοήτευση για την κοινωνία και τις προοπτικές της, η οποία εκδηλώνεται και μέσω της αποχής από τις εκλογικές επιλογές, οδηγεί σε μείωση/αναβολή «ανοιγμάτων» όπως το να κάνουμε παιδιά; Πολύ πιθανόν.</p>
<p>Ίσως και αυτή η παραπάνω εξήγηση να ερμηνεύει το γιατί τα άκυρα έχουν μια μικρότερη πτωτική πορεία (συντελεστής Spearman -0.2537596), ενώ τα λευκά μια ανοδική (συντελεστής Spearman 0.0208979), όσο μεγαλώνει η μεταβολή του πληθυσμού. Το λευκό σαν επιλογή δεν απορρίπτει τη διαδικασία, απλά εκφράζει την προσωρινή έλλειψη επιλογής. Είναι αυτό που λέμε «η συστημική εναντίωση στα πράγματα». Οπότε είναι λογικό, όσο τα πράγματα φαίνεται να μην έχουν λύση, τότε να απορρίπτεται όλο το οικοδόμημα και μαζί του και η συστημική αντίδραση του λευκού. Το άκυρο εκφράζει μιαν αγανάκτηση παραπάνω από το λευκό, αλλά όχι την έντονη απαξίωση της αποχής, ίσως και γι’ αυτό να έχει λιγότερο έντονη πτωτική τάση.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apoxi_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apoxi_files/figure-html/unnamed-chunk-19-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Προς επίρρωση των παραπάνω εκτελούμε επίσης ελέγχους Kruskal-Wallis, για να δούμε κατά πόσον ο παράγοντας «άυξηση-μείωση πληθυσμού» έχει αντίκτυπο στο ποσοστό των ακύρων και των λευκών.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  AKIRA_p by THETIKI_METABOLI
Kruskal-Wallis chi-squared = 3.9305, df = 1, p-value = 0.04742</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  LEFKA_p by THETIKI_METABOLI
Kruskal-Wallis chi-squared = 0.028877, df = 1, p-value = 0.8651</code></pre>
</div>
</div>
<p>Η μικρή p-τιμή του πρώτου ελέγχου (0.04742) δείχνει ότι είναι απίθανο να μην επιδρά ο παράγοντας στο ποσοστο των ακύρων. Από την άλλη δεν φαίνεται να έχουμε ενδείξεις ότι κάτι τέτοιο συμβαίνει και με τα λευκά (p-τιμή 0.8651).</p>
<p>Συνυπολογίζοντας τα άκυρα και τα λευκά, ώστε να έχουμε διαθέσιμα περισσότερα δεδομένα, βλέπουμε και πάλι μια πτωτική τάση. Όχι τόσο έντονη όσο της αποχής (συντελεστής Spearman -0.2977599 -0.2977599), ασθενής θα λέγαμε ότι είναι, αλλά πάντως υπαρκτή.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apoxi_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Από την άλλη έλεγχος Kruskal-Wallis (p-τιμή 0.05882) δεν επιβεβαιώνει περίτρανα ότι η μείωση πληθυσμού συνδέεται με το μέγεθος της αποχής. Αλλά αυτό κρίνεται και από το αν ο αναγνώστης θεωρεί πως το 5.882% έχει ουσιαστική διαφορά από το 5%.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  AKIRO_LEFKO_p by THETIKI_METABOLI
Kruskal-Wallis chi-squared = 3.5703, df = 1, p-value = 0.05882</code></pre>
</div>
</div>
</section>
</section>
<section id="προβλέψεις" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Προβλέψεις</h1>
<p>Πού οδηγείται η κατάσταση; Ποια θα είναι η αποχή στις επόμενες εκλογικές αναμετρήσεις; Θα κάνουμε μιαν απόπειρα να προβλέψουμε τι μέλλει γενέσθαι χρησιμοποιώντας μοντέλα ARIMA.</p>
<p>Στον κάτωθι πίνακα βλέπουμε το πού περιμένουμε να κυμαίνονται τα ποσοστά της αποχής, των ακύρων και των λευκών στις πέντε επόμενες εκλογικές αναμετρήσεις.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>           ΑΠΟΧΗ        ΑΚΥΡΟ        ΛΕΥΚΟ
1 [35.2%, 50.3%] [1.7%, 3.8%]   [0%, 1.5%]
2 [38.7%, 54.9%] [0.4%, 2.6%]   [0%, 1.9%]
3 [37.5%, 57.5%] [1.1%, 3.5%]   [0%, 1.9%]
4   [38%, 60.1%] [0.6%, 3.1%] [0.1%, 2.1%]
5 [38.7%, 63.6%] [0.9%, 3.4%] [0.1%, 2.1%]</code></pre>
</div>
</div>
<p>Τα διαστήματα σχηματίστηκαν με τρόπο που να μπορούμε να είμαστε κατά 80% βέβαιοι ότι θα πέσουμε μέσα. Αν ο βαθμός αυτός βεβαιότητας δεν μας αρκεί, θα πρέπει να διευρύνουμε κι άλλο τα διαστήματα, ώστε να γίνει πιθανότερο να πέσουν μέσα οι προβλέψεις μας. Ο ενδιαφερόμενος αναγνώστης μπορεί να επεξεργαστεί τον κώδικα, ώστε να αυξήσει τη βεβαιότητά του και να την φτάσει στο 95%.</p>
</section>
<section id="προτάσεις-για-περεταίρω-μελέτη" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Προτάσεις για περεταίρω μελέτη</h1>
<p>Στο σημείο αυτό τελειώνει η έρευνά μας. Αυτό, φυσικά, δεν σημαίνει ότι εξαντλήσαμε το ζήτημα. Το αντίθετο. Απλά κάναμε μιαν αρχή. Υπάρχουν πολλά που θα μπορούσαν να εξεταστούν επίσης. Για παράδειγμα:</p>
<ul>
<li><p>Εξαρτάται το μέγεθος της αποχής από το πιο κόμμα κυβέρνησε προηγουμένως;</p></li>
<li><p>Επηρεάστηκε το μέγεθος της αποχής από ένα δραματικό γεγονός που συνέβη, όπως ένα σιδηροδρομικό δυστύχημα ή μια πλημμύρα;</p></li>
<li><p>Η αστικοποίηση του πληθυσμού, η μετανάστευσή του μακριά από τον τόπο που ψηφίζει σχετίζεται με το μέγεθος της αποχής;</p></li>
<li><p>Η αύξηση της αποχής δηλώνει απαξίωση της εκλογικής διαδικασίας ή μήπως αντανακλά την παρακμή του ελληνικού κράτους, το οποίο δεν ενημερώνει τους εκλογικούς καταλόγους, με αποτέλεσμα να είναι εγγεγραμμένοι σε αυτούς ακόμα και οι πεθαμένοι, οπότε να φαίνεται ότι απέχουν;</p></li>
</ul>
<p>Το τελευταίο αξίζει να το μελετήσουμε λίγο παραπάνω, ώστε να στρώσουμε το δρόμο για μια νέα μελέτη.</p>
<p>Σχεδιάζοντας το χρονοδιάγραμμα των εγγεγραμμένων στους εκλογικούς καταλόγους βλέπουμε την ύπαρξη μιας έντονα αυξητικής τάσης, η οποία επιβεβαιώνεται και από τον συντελεστή μονοτονικής συσχέτισης Spearman (0.855264). Αυτό θα έλεγε κανείς ότι αντιφάσκει με το γεγονός ότι ο πληθυσμός της Ελλάδας φθίνει σε βαθμό που να αντιμετωπίζουμε δημογραφικό πρόβλημα.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apoxi_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Μήπως τελικά η αυξανόμενη αποχή αντανακλά όντως την νωθρότητα του ελληνικού κράτους; Για να απαντήσουμε αυτό το ερώτημα θα πρέπει να συγκρίνουμε τον αριθμό των εγγεγραμμένων στους εκλογικούς καταλόγους με τον αντίστοιχο πληθυσμό της Ελλάδας εκείνη τη χρονική περίοδο.</p>
<p>Αντιπαραβάλλοντας το χρονοδιάγραμμα εξέλιξης του ελληνικού πληθυσμού στο χρονοδιάγραμμα των εγγεγραμμένων στους εκλογικούς καταλόγους, βλέπουμε μια παρόμοια μορφής καμπύλες. Αρχίζει, λοιπόν, να υποχωρεί η αίσθηση παραδοξότητας.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apoxi_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Κάνοντας επίσης γράφημα διασποράς του πληθυσμού της Ελλάδας σε σχέση με τους εγγεγραμμένους στους εκλογικούς καταλόγους βλέπουμε ότι αυτό είναι σχεδόν ευθεία γραμμή. Η πολύ ισχυρή γραμμική συσχέτισή τους επιβεβαιώνεται και από τον συντελεστή γραμμικής συσχέτισης Pearson , ο οποίος έχει τη μεγάλη τιμή 0.9413894.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apoxi_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Συγκεκριμένα βρίσκουμε ότι:</p>
<blockquote class="blockquote">
<p>[εγγεγραμμένοι] = 1.995·[πληθυσμός]-11’820’000</p>
</blockquote>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = simetoxiN_EU$EGGEGRAMMENOI ~ plithismosGR)

Coefficients:
 (Intercept)  plithismosGR  
  -1.182e+07     1.995e+00  </code></pre>
</div>
</div>
<p>Ας το μελετήσουμε όμως άλλο λίγο. Αρχικά θα θεωρήσουμε ότι οι εγγεγραμμένοι στους εκλογικούς καταλόγους είναι οι Έλληνες ενήλικες.</p>
<p>Κάνοντας το χρονογράφημα του ποσοστού των ενηλίκων μαζί με την καμπύλη τοπικής παλινδρόμησης βλέπουμε ότι αυτό αυξάνεται στην πάροδο του χρόνου. Αυτό εναρμονίζεται με όσα γνωρίζουμε για την γήρανση του πληθυσμού, όσο υπάρχει υπογεννητικότητα.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apoxi_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Δεν φαίνεται να υπάρχει κάποιο πρόβλημα με τα δεδομένα μας λοιπόν. Μια σοβαρή όμως ανάλυση θα απαιτούσε να συνεξετάσουμε την αρχική ηλικιακή κατανομή του πληθυσμού της Χώρας, την παιδική θνησιμότητα, το προσδόκιμο ζωής κ.τ.λ. Αυτά όμως ξεφεύγουν από τη θεματολογία αυτού του άρθρου και αποτελούν αντικείμενο μιας άλλης μελλοντικής έρευνας.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>