{
  "hash": "7e1665b182f7357b1b1e160af178bd82",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Εκθετική κατανομή\"\nauthor: \"Κώστας Κούδας\"\ncache: TRUE\ndate: \"2026-02-11\"\nformat:\n  html:\n    toc: true\n    number-sections: true\n    fig-cap: true\n---\n\n\n\n\n::: {.cell}\n\n:::\n\n\n<mark>Ας υποθέσουμε ότι ένα γεγονός εμφανίζεται με έναν συγκεκριμένο μέσο ρυθμό σε κάποιο χρονικό διάστημα (ή σε κάποια περιοχή του χώρου). Ο χρόνος μεταξύ δύο διαδοχικών εμφανίσεων του γεγονότος αυτού ακολουθεί την **εκθετική κατανομή**.</mark>\n\nΑς επανέλθουμε στο παράδειγμα με την ωριαία πελατεία ενός καταστήματος που είχαμε δει στην ενότητα [Κατανομή Poisson](poisson.html). Είπαμε ότι στο κατάστημα μπαίνουν κάθε ώρα κατά μέσο όρο 8 πελάτες ή, με άλλα λόγια, το χρονικό διάστημα από την είσοδο του ενός πελάτη έως του επόμενου είναι κατά μέσο όρο το ⅛ της ώρας. Θέλουμε να μελετήσουμε χρονικό διάστημα θα μεσολαβεί από την είσοδο του ενός μέχρι την είσοδο του άλλου. Είπαμε ότι κατά μέσο όρο είναι το ⅛ της ώρας. Πόσο πιθανό, όμως είναι, να κάνει να μπει κάποιος πελάτης 1 ολόκληρη ώρα ή μισή ώρα; Φυσικά, δεν μας απασχολεί αν κάποιος καθίσει ώρα μέσα στο κατάστημα και μπούνε κι άλλοι κατά τη διάρκεια που είναι αυτός μέσα. Εμείς μετράμε το χρόνο από τη στιγμή που ακούστηκε το «ντιν» στο κουδουνάκι της εισόδου, μέχρι το επόμενο «ντιν».\n\nΘα καταγράψουμε το χρόνο μεταξύ των εισόδων 1000 πελατών κι αυτό θα το κάνουμε 4 φορές. Γράφουμε λοιπόν:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar( mfrow= c(2,2) )\nfor (i in 1:4) {\n  set.seed(100*i)\n  xilioi_pelates <- rexp(1000, 8) \n  hist(xilioi_pelates)\n}\n```\n\n::: {.cell-output-display}\n![](expDist_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nΠάμε τώρα να δούμε τι μας λένε αυτά τα ιστογράμματα. Μας λένε ότι ως επί το πλείστον θα μεσολαβούν από 0 έως 0.1 ώρες (από 0 λεπτά έως 6 λεπτά) από την άφιξη ενός πελάτη, έως και την άφιξη του επόμενου. Είναι, λένε τα ιστογράμματα, σχεδόν απίθανο να μεσολαβήσουν 0.5-0.6 ώρες (30-36 λεπτά) μεταξύ των αφίξεων δύο πελατών.\n\nΑς δούμε όμως τώρα ένα πιο συγκεκριμένο ερώτημα. Πόση είναι η πιθανότητα να μεσολαβήσουν 9 με 15 λεπτά (0.15 με 0.25 ώρες) μεταξύ δύο διαδοχικών αφίξεων; Γράφουμε:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npexp(0.25,  8)-pexp(0.15,  8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1658589\n```\n\n\n:::\n:::\n\n\nκαι βρίσκουμε 0.1658589. Επομένως μπορούμε να είμαστε μόνο κατά 16.59% σίγουροι ότι θα μεσολαβήσουν 9-15 λεπτά μεταξύ των αφίξεων δύο πελατών.\n\nΌλος ο κώδικας που γράψαμε είναι ο κάτωθι:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar( mfrow= c(2,2) )\nfor (i in 1:4) {\n  set.seed(100*i)\n  xilioi_pelates <- rexp(1000, 8) \n  hist(xilioi_pelates)\n}\npexp(0.25,  8)-pexp(0.15,  8)\n```\n:::\n\n\n\n\n\n\n\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}